(() => {
'use strict';
const {configured,supabase,escapeHtml:esc,shortDate,toast,run,checked,allRows,requireBackend,saveRow,modal,openPrivateFile,listTeamFiles,humanError,setupPanel}=window.Portal;
const state={user:null,profile:null,section:'overview',cohorts:[],teams:[],people:[],projects:[],reviews:[],assignments:[]};const $=s=>document.querySelector(s);const admin=()=>state.profile?.global_role==='admin';
document.addEventListener('DOMContentLoaded',initializeAdmin);
async function initializeAdmin(){try{
 if(!configured||!supabase){$('#admin-config').innerHTML=setupPanel();$('#admin-config').classList.remove('hidden');return;}
 const {session}=await checked(supabase.auth.getSession());if(!session)return deny();state.user=session.user;
 await requireBackend();state.profile=await checked(supabase.from('profiles').select('*').eq('id',state.user.id).single());if(!allowed())return deny();
 $('#admin-nav').onclick=event=>{const b=event.target.closest('[data-admin-section]');if(b){state.section=b.dataset.adminSection;render();}};
 $('#admin-content').onclick=handleClick;$('#admin-content').onchange=handleChange;$('#admin-content').onsubmit=handleSubmit;
 document.querySelector('[data-signout]').onclick=e=>run(e.currentTarget,async()=>{await checked(supabase.auth.signOut());location.href='index.html';});
 window.addEventListener('beforeunload',event=>{if(document.querySelector('dialog[data-dirty="true"]')){event.preventDefault();event.returnValue='';}});
 await reload();$('#admin-app').classList.remove('hidden');
 }catch(error){$('#admin-config').innerHTML=`<section class="setup-panel"><h2>No se pudo cargar administración</h2><p>${esc(humanError(error))}</p><button class="primary-btn" onclick="location.reload()">Reintentar</button></section>`;$('#admin-config').classList.remove('hidden');}}
function allowed(){return state.profile?.status==='active'&&!state.profile.deleted_at&&['admin','docente'].includes(state.profile.global_role);}
function deny(){$('#admin-app').classList.add('hidden');$('#admin-denied').classList.remove('hidden');}
async function reload(){const result=await Promise.all([allRows(()=>supabase.from('cohorts').select('*').order('id')),allRows(()=>supabase.from('academic_teams').select('*,cohort:cohorts(name,year),members:team_members(user_id,role,status,profile:profiles(full_name,email,status))').order('id')),allRows(()=>supabase.from('profiles').select('*').order('id')),allRows(()=>supabase.from('projects').select('*,team:academic_teams(name,modality),deliverables(*)').order('id')),allRows(()=>supabase.from('jury_reviews').select('*,reviewer:profiles(full_name,email),project:projects(title)').order('id')),allRows(()=>supabase.from('jury_assignments').select('*').order('project_id').order('reviewer_id'))]);[state.cohorts,state.teams,state.people,state.projects,state.reviews,state.assignments]=result;state.profile=state.people.find(p=>p.id===state.user.id);if(!allowed()){deny();return;}state.people=state.people.filter(p=>!p.deleted_at);$('#admin-name').textContent=state.profile.full_name||state.profile.email;render();}
function head(title,description='',actions=''){return `<header class="section-head"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${actions}</header>`;}
function empty(text){return `<div class="empty-state">${esc(text)}</div>`;}
function render(){document.querySelectorAll('[data-admin-section]').forEach(b=>b.classList.toggle('active',b.dataset.adminSection===state.section));$('#admin-content').innerHTML=({overview,teams,people,deliverables,reviews}[state.section])();}
function overview(){return `${head('Visión general','Avance calculado por la base; incluye entregas aprobadas.')}<section class="admin-stats"><article><span>Equipos</span><strong>${state.teams.length}</strong></article><article><span>Personas activas</span><strong>${state.people.filter(p=>p.status==='active').length}</strong></article><article><span>Proyectos</span><strong>${state.projects.length}</strong></article><article><span>Entregas por revisar</span><strong>${state.projects.flatMap(p=>p.deliverables||[]).filter(d=>d.status==='submitted').length}</strong></article></section><section class="admin-table-card"><div class="project-admin-rows">${state.projects.map(p=>`<article><div><strong>${esc(p.title)}</strong><small>${esc(p.team?.name)}</small></div><span>${esc(p.status)}</span><b>${p.progress}%</b><a href="index.html?team=${encodeURIComponent(p.team_id)}">Supervisar</a></article>`).join('')||empty('No hay proyectos.')}</div></section>`;}
function teams(){return `${head('Equipos de trabajo','Supervise proyectos, integrantes, invitaciones y estado.','<button class="primary-btn" data-create-team>Crear equipo</button>')}<div class="team-admin-grid">${state.teams.map(t=>{const active=(t.members||[]).filter(m=>m.status==='active');return `<article class="team-admin-card"><div><strong>${esc(t.name)}</strong><p>${esc(t.modality)} · ${active.length}/${t.max_members} · ${esc(t.status)}</p></div><a class="ghost-btn button-link" href="index.html?team=${encodeURIComponent(t.id)}">Entrar al espacio</a><button class="ghost-btn" data-members="${esc(t.id)}">Gestionar integrantes</button>${['forming','active'].includes(t.status)?`<button class="ghost-btn" data-invite="${esc(t.id)}">Gestionar invitaciones</button>`:''}${t.status!=='deleting'?`<button class="text-btn" data-team-status="${esc(t.id)}" data-next-status="${t.status==='archived'?'active':'archived'}">${t.status==='archived'?'Reabrir':'Archivar'}</button><button class="text-btn" data-edit-team="${esc(t.id)}">Editar equipo</button>`:''}${admin()?`<button class="danger-btn" data-delete-team="${esc(t.id)}">${t.status==='deleting'?'Reintentar eliminación':'Eliminar equipo'}</button>`:''}</article>`;}).join('')||empty('Cree el primer equipo.')}</div>`;}
function people(){return `${head('Participantes y roles','Solo administradores pueden cambiar permisos globales y estado.')}<section class="admin-table-card"><div class="people-table table">${state.people.map(p=>`<div class="tr"><span><strong>${esc(p.full_name||p.email)}</strong><small>${esc(p.email)}</small>${admin()&&p.id!==state.user.id?`<button class="danger-btn" data-delete-person="${esc(p.id)}">Eliminar persona</button>`:''}</span><label>Rol de ${esc(p.full_name||p.email)}<select data-role="${esc(p.id)}" ${!admin()&&!['participante','lider'].includes(p.global_role)?'disabled':''}>${(admin()?['participante','lider','docente','jurado','admin']:['participante','lider'].includes(p.global_role)?['participante','lider']:[p.global_role]).map(r=>`<option value="${r}" ${r===p.global_role?'selected':''}>${esc(r)}</option>`).join('')}</select></label><label>Acceso de ${esc(p.full_name||p.email)}<select data-status="${esc(p.id)}" ${admin()?'':'disabled'}>${['active','pending','blocked'].map(s=>`<option value="${s}" ${s===p.status?'selected':''}>${s}</option>`).join('')}</select></label><span>${shortDate(p.created_at)}</span></div>`).join('')}</div></section>`;}
function allDeliverables(){return state.projects.flatMap(p=>(p.deliverables||[]).map(d=>({...d,project:p})));}
function deliverables(){return `${head('Entregables académicos','Revise archivos privados, ajuste vencimientos y registre retroalimentación.')}<section class="deliverable-admin-list">${allDeliverables().sort((a,b)=>a.due_at.localeCompare(b.due_at)).map(d=>`<article><div><span class="status ${esc(d.status)}">${esc(d.status)}</span><strong>${esc(d.title)}</strong><small>${esc(d.project.title)} · ${esc(d.project.team?.name)}</small></div><time>${shortDate(d.due_at)}</time>${d.file_path?`<button class="ghost-btn" data-open-file="${esc(d.file_path)}">Abrir archivo</button>`:'<span>Sin archivo</span>'}<button class="text-btn" data-review="${esc(d.id)}">Revisar entrega</button></article>`).join('')||empty('No hay entregables.')}</section>`;}
function reviews(){return `${head('Evaluación de impacto','Asignaciones vigentes y valoraciones recibidas.')}<section class="admin-table-card">${state.projects.map(p=>{const assigned=state.assignments.filter(a=>a.project_id===p.id);return `<article class="review-project"><div><strong>${esc(p.title)}</strong><small>${esc(p.team?.name)}</small>${assigned.map(a=>`<p>${esc(state.people.find(x=>x.id===a.reviewer_id)?.full_name||'Usuario retirado')} <button class="danger-btn" data-unassign="${esc(a.reviewer_id)}" data-project="${esc(p.id)}">Retirar asignación</button></p>`).join('')}</div><form data-form="jury"><input type="hidden" name="project_id" value="${esc(p.id)}"><label>Jurado para ${esc(p.title)}<select name="reviewer_id" required><option value="">Seleccionar…</option>${state.people.filter(x=>x.global_role==='jurado'&&x.status==='active'&&!assigned.some(a=>a.reviewer_id===x.id)).map(x=>`<option value="${esc(x.id)}">${esc(x.full_name||x.email)}</option>`).join('')}</select></label><button class="ghost-btn">Asignar</button></form></article>`;}).join('')}</section><section class="review-summary"><h3>Evaluaciones recibidas</h3>${state.reviews.map(r=>{const scores=[r.strategic_impact,r.feasibility,r.innovation,r.evidence_quality,r.presentation];const complete=scores.every(Number.isFinite);return `<article><strong>${esc(r.project?.title)}</strong><span>${esc(r.reviewer?.full_name||r.reviewer?.email)}</span><b>${complete?(scores.reduce((a,b)=>a+b,0)/5).toFixed(1)+'/5':'Incompleta'}</b><p>${esc(r.comments)}</p></article>`;}).join('')||empty('Sin evaluaciones.')}</section>`;}
function handleSubmit(event){event.preventDefault();const form=event.target.closest('form[data-form="jury"]');if(!form)return;const values=Object.fromEntries(new FormData(form));return run(event.submitter,async()=>{await checked(supabase.from('jury_assignments').upsert(values,{onConflict:'project_id,reviewer_id'}));await reload();toast('Jurado asignado.');});}
function handleChange(event){const input=event.target;if(!input.dataset.role&&!input.dataset.status)return;const p=state.people.find(p=>p.id===(input.dataset.role||input.dataset.status));const old=input.dataset.role?p.global_role:p.status;run(input,async()=>{try{if(input.dataset.role&&!admin())await checked(supabase.rpc('set_team_leader_permission',{p_profile:p.id,p_enabled:input.value==='lider'}));else await checked(supabase.from('profiles').update(input.dataset.role?{global_role:input.value}:{status:input.value}).eq('id',p.id).select().single());await reload();toast('Perfil actualizado.');}catch(error){input.value=old;throw error;}});}
function handleClick(event){const b=event.target.closest('button');if(!b)return;if(b.dataset.openFile)return openPrivateFile(b.dataset.openFile,b);if(b.hasAttribute('data-create-team'))return teamModal();if(b.dataset.editTeam)return teamModal(state.teams.find(t=>t.id===b.dataset.editTeam));if(b.dataset.invite)return invitationModal(state.teams.find(t=>t.id===b.dataset.invite));if(b.dataset.members)return membersModal(state.teams.find(t=>t.id===b.dataset.members));if(b.dataset.review)return reviewModal(allDeliverables().find(d=>d.id===b.dataset.review));if(b.dataset.deletePerson)return personDeleteModal(state.people.find(p=>p.id===b.dataset.deletePerson));if(b.dataset.deleteTeam)return teamDeleteModal(state.teams.find(t=>t.id===b.dataset.deleteTeam));if(b.dataset.teamStatus)return run(b,async()=>{await checked(supabase.from('academic_teams').update({status:b.dataset.nextStatus}).eq('id',b.dataset.teamStatus).select().single());await reload();toast('Estado del equipo actualizado.');});if(b.dataset.unassign&&confirm('¿Retirar la asignación? La evaluación registrada se conservará.'))return run(b,async()=>{await checked(supabase.from('jury_assignments').delete().eq('project_id',b.dataset.project).eq('reviewer_id',b.dataset.unassign));await reload();toast('Asignación retirada.');});}
function teamModal(team){const d=modal(`<h2>${team?'Editar':'Crear'} equipo</h2><form class="modal-form"><label>Cohorte<select name="cohort_id" ${team?'disabled':''}>${state.cohorts.map(c=>`<option value="${esc(c.id)}" ${team?.cohort_id===c.id?'selected':''}>${esc(c.name)} · ${c.year}</option>`).join('')}</select></label><label>Nombre<input name="name" minlength="3" maxlength="80" value="${esc(team?.name||'')}" required></label><label>Modalidad<select name="modality"><option value="presencial">Presencial</option><option value="remoto" ${team?.modality==='remoto'?'selected':''}>Remoto</option></select></label><label>Capacidad<input name="max_members" type="number" min="3" max="8" required value="${team?.max_members||4}"></label><button class="primary-btn">Guardar equipo</button></form>`,'Equipo');d.querySelector('form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.max_members=Number(values.max_members);if(!team)values.created_by=state.user.id;run(e.submitter,async()=>{await checked(team?supabase.from('academic_teams').update(values).eq('id',team.id).select().single():supabase.from('academic_teams').insert(values).select().single());d.dataset.dirty='false';d.close();await reload();toast('Equipo guardado.');});};}
function invitationModal(team){const code='GM26-'+Array.from(crypto.getRandomValues(new Uint8Array(12)),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase();const d=modal(`<h2>Invitaciones · ${esc(team.name)}</h2><form class="modal-form"><label>Código<input name="code" value="${code}" readonly></label><button class="primary-btn">Activar código</button></form><div class="code-result"></div><div class="code-list"></div>`,'Invitaciones');const load=async()=>{const list=await allRows(()=>supabase.from('invitations').select('id,created_at,revoked_at,use_count').eq('team_id',team.id).order('created_at'));d.querySelector('.code-list').innerHTML=list.map(i=>`<p>${shortDate(i.created_at)} · ${i.use_count} ingresos ${i.revoked_at?'Revocada':`<button data-revoke="${esc(i.id)}">Revocar</button>`}</p>`).join('');};run(null,load);d.querySelector('form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;run(e.submitter,async()=>{await checked(supabase.rpc('create_invitation',{p_team:team.id,raw_code:code,p_role:'integrante',p_max_uses:2147483647,p_expires_at:null}));form.classList.add('hidden');d.dataset.dirty='false';d.querySelector('.code-result').innerHTML=`<strong>${code}</strong><button class="ghost-btn" data-copy>Copiar código</button>`;await load();});};d.onclick=e=>{const b=e.target.closest('button');if(b?.hasAttribute('data-copy'))run(b,async()=>{await navigator.clipboard.writeText(code);toast('Código copiado.');});if(b?.dataset.revoke)run(b,async()=>{await checked(supabase.rpc('revoke_invitation',{p_invitation:b.dataset.revoke}));await load();});};}
function membersModal(team){const members=(team.members||[]).filter(m=>m.status==='active');const d=modal(`<h2>Integrantes · ${esc(team.name)}</h2>${members.map(m=>`<form class="modal-form" data-user="${esc(m.user_id)}"><strong>${esc(m.profile?.full_name||m.profile?.email)}</strong><label>Rol en el equipo<select name="role">${['lider','integrante','observador'].map(r=>`<option value="${r}" ${r===m.role?'selected':''}>${r}</option>`).join('')}</select></label><button class="ghost-btn" name="action" value="save">Guardar rol</button><button class="danger-btn" name="action" value="remove">Retirar del equipo</button></form>`).join('')||'<p>No hay integrantes. Habilite un líder para reclamar este equipo.</p>'}`,'Integrantes');d.addEventListener('submit',e=>{e.preventDefault();const form=e.target;const remove=e.submitter.value==='remove';if(remove&&!confirm('¿Retirar esta persona del equipo?'))return;run(e.submitter,async()=>{await checked(supabase.rpc('set_team_member',{p_team:team.id,p_user:form.dataset.user,p_role:form.elements.role.value,p_remove:remove}));d.dataset.dirty='false';d.close();await reload();membersModal(state.teams.find(t=>t.id===team.id));toast('Membresía actualizada.');});});}
function reviewModal(item){const date=new Date(item.due_at);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);const d=modal(`<h2>${esc(item.title)}</h2><form class="modal-form"><label>Título<input name="title" value="${esc(item.title)}" required></label><label>Vencimiento<input name="due_at" type="datetime-local" value="${local}" required></label><label>Resultado<select name="status">${['pending','submitted','in_review','changes_requested','approved'].map(s=>`<option value="${s}" ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Retroalimentación<textarea name="reviewer_feedback">${esc(item.reviewer_feedback)}</textarea></label><button class="primary-btn">Guardar revisión</button></form>`,'Revisión de entrega');d.querySelector('form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.due_at=new Date(values.due_at).toISOString();run(e.submitter,async()=>{await saveRow('deliverables',values,item);d.dataset.dirty='false';d.close();await reload();toast('Revisión guardada.');});};}
function personDeleteModal(person){const d=modal(`<h2>Eliminar persona</h2><p>La cuenta quedará bloqueada y se retirarán sus membresías y asignaciones. Sus aportes se conservan.</p><p>Escriba ${esc(person.email)}.</p><form class="modal-form"><label>Correo de confirmación<input name="confirmation" type="email" required></label><button class="danger-solid-btn">Eliminar persona</button></form>`,'Eliminar persona');d.querySelector('form').onsubmit=e=>{e.preventDefault();if(e.currentTarget.elements.confirmation.value.trim().toLowerCase()!==person.email.toLowerCase())return toast('El correo no coincide.','error');run(e.submitter,async()=>{await checked(supabase.rpc('admin_remove_person',{p_profile:person.id}));d.dataset.dirty='false';d.close();await reload();toast('Persona retirada.');});};}
function teamDeleteModal(team){const d=modal(`<h2>Eliminar equipo</h2><p>Se eliminarán sus datos académicos y todas las versiones de archivos. Si la conexión falla, podrá reintentar desde el equipo marcado en eliminación.</p><p>Escriba exactamente ${esc(team.name)}.</p><form class="modal-form"><label>Nombre de confirmación<input name="confirmation" required></label><button class="danger-solid-btn">Eliminar equipo definitivamente</button></form>`,'Eliminar equipo');d.querySelector('form').onsubmit=e=>{e.preventDefault();const confirmation=e.currentTarget.elements.confirmation.value.trim();if(confirmation!==team.name)return toast('El nombre no coincide.','error');run(e.submitter,async()=>{await checked(supabase.rpc('prepare_team_deletion',{p_team:team.id,p_confirmation:confirmation}));const files=await listTeamFiles(team.id);for(let start=0;start<files.length;start+=100)await checked(supabase.storage.from('deliverables').remove(files.slice(start,start+100)));await checked(supabase.rpc('admin_delete_team',{p_team:team.id,p_confirmation:confirmation}));d.dataset.dirty='false';d.close();await reload();toast('Equipo y archivos eliminados.');});};}
})();
