(() => {
'use strict';
const {config,configured,supabase,escapeHtml:esc,shortDate,money,toast,run,checked,allRows,saveRow,requireBackend,modal,openPrivateFile,humanError,setupPanel}=window.Portal;
const $=selector=>document.querySelector(selector);
const show=selector=>$(selector)?.classList.remove('hidden');
const hide=selector=>$(selector)?.classList.add('hidden');
const SECTIONS=[['overview','Inicio','00'],['members','Equipo','M'],['diagnosis','Diagnóstico','01'],['objectives','Objetivos SMART','02'],['alternatives','Alternativas','03'],['action','Plan de acción','04'],['people','Involucrados','05'],['indicators','Indicadores','06'],['prototype','Prototipo','P'],['deliverables','Entregables','E'],['comments','Comentarios','C'],['activity','Historial','H']];
const state={user:null,profile:null,team:null,membership:null,project:null,section:'overview',participants:[],perspectives:[],objectives:[],alternatives:[],actions:[],stakeholders:[],resources:[],indicators:[],deliverables:[],versions:[],comments:[],activity:[],diagnosis:null,prototype:null,realtime:null,administrativeAccess:false,editing:null,loadError:false};
const dirtyForms=new Set();let remotePending=false,refreshInFlight=false,refreshRequested=false,loadGeneration=0;
let recoveryMode=window.portalRecoveryRedirect===true||new URLSearchParams(location.hash.slice(1)).get('type')==='recovery'||new URLSearchParams(location.search).get('type')==='recovery';
const facilitator=()=>['admin','docente'].includes(state.profile?.global_role);
const canEdit=()=>state.profile?.status==='active'&&!state.profile?.deleted_at&&!['archived','deleting'].includes(state.team?.status)&&(facilitator()||['lider','integrante'].includes(state.membership?.role));
const hasDraft=()=>dirtyForms.size>0||!!document.querySelector('dialog[data-dirty="true"]');
const canLeave=()=>!hasDraft()||confirm('Tiene cambios sin guardar. ¿Descartarlos y continuar?');
const one=(table,id,key='project_id')=>checked(supabase.from(table).select('*').eq(key,id).maybeSingle(),table);
const rows=(table,id)=>allRows(()=>supabase.from(table).select('*').eq('project_id',id).order('id'));

document.addEventListener('DOMContentLoaded',initialize);
async function initialize(){
 try{
  if(!configured||!supabase){$('#config-view').innerHTML=setupPanel();hide('#boot-view');show('#config-view');return;}
  wire();
  supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;showRecovery();}else if(!session&&!recoveryMode){stopRealtime();showAuth();}});
  const data=await checked(supabase.auth.getSession());
  if(recoveryMode&&data.session)showRecovery();else if(data.session)await enterPortal(data.session.user);else showAuth();
 }catch(error){fatal(error);}
}
function wire(){
 document.querySelectorAll('[data-auth-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b===button));$('#login-form').classList.toggle('hidden',button.dataset.authTab!=='login');$('#signup-form').classList.toggle('hidden',button.dataset.authTab!=='signup');});
 $('#login-form').onsubmit=login;$('#signup-form').onsubmit=signup;$('#password-reset-form').onsubmit=updatePassword;
 $('#join-form').onsubmit=joinTeam;$('#leader-team-form').onsubmit=createTeamAsLeader;$('#forgot-password').onclick=forgotPassword;
 document.querySelectorAll('[data-signout]').forEach(button=>button.onclick=()=>{if(canLeave())run(button,async()=>{await checked(supabase.auth.signOut());stopRealtime();location.href='index.html';});});
 $('#team-invite-btn').onclick=teamInvitationModal;$('#download-draft').onclick=e=>downloadWordDraft(e.currentTarget);
 $('#print-project').onclick=()=>{if(hasDraft())toast('La impresión muestra la sección actual. Guarde sus cambios antes de imprimir.','error');else window.print();};
 $('#course-nav').onclick=event=>{const b=event.target.closest('[data-section]');if(!b||!canLeave())return;dirtyForms.clear();state.editing=null;state.section=b.dataset.section;renderNavigation();renderSection();if(remotePending)refreshProject();};
 $('#project-content').addEventListener('input',event=>{const f=event.target.closest('form');if(f)dirtyForms.add(f);});
 $('#project-content').addEventListener('change',event=>{const f=event.target.closest('form');if(f)dirtyForms.add(f);});
 $('#project-content').addEventListener('submit',handleSubmit);$('#project-content').addEventListener('click',handleClick);
 window.addEventListener('beforeunload',event=>{if(hasDraft()){event.preventDefault();event.returnValue='';}});
 window.addEventListener('online',()=>{toast('Conexión recuperada. Puede guardar o actualizar los datos.');});
 window.addEventListener('offline',()=>toast('Sin conexión. Mantenga esta página abierta para conservar lo que está escribiendo.','error'));
 const banner=document.createElement('div');banner.id='updates-banner';banner.className='update-banner hidden';banner.setAttribute('role','status');banner.innerHTML='<span>Hay cambios recientes o una lectura pendiente. Su borrador se conserva.</span><button type="button" class="ghost-btn">Actualizar datos</button>';
 $('.course-main').prepend(banner);banner.querySelector('button').onclick=()=>{if(canLeave()){dirtyForms.clear();state.editing=null;refreshProject(true);}};
}
function showAuth(){['#boot-view','#config-view','#app-view','#join-view','#password-reset-view'].forEach(hide);show('#auth-view');}
function showRecovery(){['#boot-view','#config-view','#app-view','#join-view','#auth-view'].forEach(hide);show('#password-reset-view');}
function fatal(error){['#auth-view','#app-view','#join-view','#password-reset-view'].forEach(hide);$('#boot-view').innerHTML=`<section class="setup-panel"><h2>No se pudo cargar el portal</h2><p>${esc(humanError(error))}</p><button class="primary-btn" onclick="location.reload()">Intentar nuevamente</button></section>`;show('#boot-view');}
function login(event){event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));return run(event.submitter,async()=>{const data=await checked(supabase.auth.signInWithPassword({email:values.email.trim(),password:values.password}));await enterPortal(data.user);},'Ingresando…');}
function signup(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));return run(event.submitter,async()=>{const data=await checked(supabase.auth.signUp({email:values.email.trim(),password:values.password,options:{data:{full_name:values.full_name.trim()},emailRedirectTo:new URL('index.html',location.href).href}}));if(data.session)await enterPortal(data.user);else toast('Revise su correo y confirme la cuenta antes de ingresar.');},'Creando cuenta…');}
function updatePassword(event){event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));if(values.password!==values.confirmation||values.password.length<8)return toast('Use al menos 8 caracteres y confirme la misma contraseña.','error');return run(event.submitter,async()=>{await checked(supabase.auth.updateUser({password:values.password}));await checked(supabase.auth.signOut());recoveryMode=false;history.replaceState({},'',new URL('index.html',location.href));form.reset();showAuth();toast('Contraseña actualizada. Ingrese con su nueva contraseña.');},'Actualizando…');}
function forgotPassword(event){const email=$('#login-form [name="email"]').value.trim();if(!email)return toast('Escriba primero su correo.','error');return run(event.currentTarget,async()=>{await checked(supabase.auth.resetPasswordForEmail(email,{redirectTo:new URL('index.html',location.href).href}));toast('Si la cuenta está registrada, recibirá instrucciones de recuperación.');});}
async function enterPortal(user){
 state.user=user;await requireBackend();
 const profile=await one('profiles',user.id,'id');if(!profile)throw new Error('No se encontró el perfil');
 if(profile.status!=='active'||profile.deleted_at){await checked(supabase.auth.signOut());showAuth();toast('Esta cuenta fue deshabilitada. Consulte al administrador.','error');return;}
 state.profile=profile;if(profile.global_role==='jurado'){location.href='jury.html';return;}
 const requested=new URLSearchParams(location.search).get('team');state.administrativeAccess=!!requested&&facilitator();
 if(state.administrativeAccess){state.team=await checked(supabase.from('academic_teams').select('*,cohort:cohorts(name,year)').eq('id',requested).single());state.membership={role:'facilitador'};}
 else {const membership=await checked(supabase.from('team_members').select('role,status,team:academic_teams(*,cohort:cohorts(name,year))').eq('user_id',user.id).eq('status','active').maybeSingle());state.membership=membership;state.team=membership?.team;}
 ['#boot-view','#auth-view','#password-reset-view'].forEach(hide);
 if(!state.team){renderMembershipCenter();return;}
 await loadWorkspace();hide('#join-view');show('#app-view');
}
function renderMembershipCenter(){hide('#app-view');show('#join-view');$('#membership-name').textContent=state.profile.full_name||'Cuenta académica';$('#membership-email').textContent=state.profile.email;$('#membership-role').textContent=state.profile.global_role;$('#leader-create-card').classList.toggle('hidden',state.profile.global_role!=='lider');$('#leader-wait-card').classList.toggle('hidden',state.profile.global_role==='lider');$('#membership-admin-link').classList.toggle('hidden',!facilitator());}
function joinTeam(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));return run(event.submitter,async()=>{await checked(supabase.rpc('join_with_invitation',{raw_code:values.invitation,participant_name:state.profile.full_name||state.profile.email}));await enterPortal(state.user);toast('Ya hace parte del equipo.');});}
function createTeamAsLeader(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));return run(event.submitter,async()=>{await checked(supabase.rpc('create_team_as_leader',{p_name:values.name,p_modality:values.modality,p_max_members:Number(values.max_members)}));await enterPortal(state.user);toast('Equipo creado.');});}
async function loadWorkspace(){
 const [perspectives,project,participants]=await Promise.all([allRows(()=>supabase.from('strategic_perspectives').select('*').order('sort_order')),one('projects',state.team.id,'team_id'),checked(supabase.rpc('get_team_participants',{p_team:state.team.id}))]);
 const data=project?await fetchProjectData(project.id):{};Object.assign(state,data,{perspectives,project,participants,loadError:false});
 $('#profile-name').textContent=state.profile.full_name||state.profile.email;$('#team-label').textContent=`${state.team.name} · ${state.team.modality}`;$('#admin-link').classList.toggle('hidden',!facilitator());$('#team-invite-btn').classList.toggle('hidden',state.membership?.role!=='lider'||!canEdit());$('#admin-workspace-banner').classList.toggle('hidden',!state.administrativeAccess);$('#admin-workspace-team').textContent=state.team.name;
 renderNavigation();if(!project){renderCreateProject();return;}hide('#project-empty');show('#project-content');renderSection();subscribeRealtime();
}
async function fetchProjectData(id){
 const keys=['diagnosis','objectives','alternatives','actions','stakeholders','resources','indicators','prototype','deliverables','versions','comments','activity'];
 const values=await Promise.all([one('problem_diagnosis',id),rows('project_objectives',id),rows('solution_alternatives',id),rows('action_plan',id),rows('stakeholders',id),rows('project_resources',id),rows('indicators',id),one('prototype',id),rows('deliverables',id),rows('deliverable_versions',id),allRows(()=>supabase.rpc('get_project_comments',{p_project:id}).order('created_at',{ascending:false})),allRows(()=>supabase.from('activity_log').select('*').eq('project_id',id).order('id',{ascending:false}))]);
 return Object.fromEntries(keys.map((key,index)=>[key,values[index]]));
}
async function refreshProject(explicit=false){
 if(!state.project)return;if(refreshInFlight){refreshRequested=true;return;}if(hasDraft()&&!explicit){remotePending=true;show('#updates-banner');return;}
 refreshInFlight=true;const generation=++loadGeneration;
 try{
  const profile=await one('profiles',state.user.id,'id');
  if(!profile||profile.status!=='active'||profile.deleted_at){await checked(supabase.auth.signOut());showAuth();return;}
  const [project,team,participants]=await Promise.all([one('projects',state.project.id,'id'),one('academic_teams',state.team.id,'id'),checked(supabase.rpc('get_team_participants',{p_team:state.team.id}))]);
  if(!project||!team)throw new Error('El proyecto ya no está disponible o perdió acceso.');
  const [data,membership]=await Promise.all([fetchProjectData(project.id),state.administrativeAccess?Promise.resolve(state.membership):checked(supabase.from('team_members').select('role,status').eq('team_id',team.id).eq('user_id',state.user.id).eq('status','active').maybeSingle())]);
  if(generation!==loadGeneration)return;
  if(hasDraft()){remotePending=true;show('#updates-banner');return;}
  Object.assign(state,data,{project,profile,team,participants,membership,loadError:false});
  remotePending=false;hide('#updates-banner');renderNavigation();renderSection();
 }catch(error){state.loadError=true;remotePending=true;show('#updates-banner');toast(humanError(error),'error');}
 finally{refreshInFlight=false;if(refreshRequested){refreshRequested=false;setTimeout(()=>refreshProject(),0);}}
}
function stopRealtime(){if(state.realtime)supabase.removeChannel(state.realtime);state.realtime=null;loadGeneration++;}
function subscribeRealtime(){stopRealtime();let timer;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>refreshProject(),500);};const channel=supabase.channel(`project-${state.project.id}`);
 for(const table of ['problem_diagnosis','project_objectives','solution_alternatives','action_plan','stakeholders','project_resources','indicators','prototype','deliverables','project_comments'])channel.on('postgres_changes',{event:'*',schema:'public',table,filter:`project_id=eq.${state.project.id}`},refresh);
 channel.on('postgres_changes',{event:'*',schema:'public',table:'projects',filter:`id=eq.${state.project.id}`},refresh);
 channel.on('postgres_changes',{event:'*',schema:'public',table:'team_members',filter:`team_id=eq.${state.team.id}`},refresh);
 channel.on('postgres_changes',{event:'*',schema:'public',table:'academic_teams',filter:`id=eq.${state.team.id}`},refresh);
 channel.on('postgres_changes',{event:'*',schema:'public',table:'profiles',filter:`id=eq.${state.user.id}`},refresh);
 state.realtime=channel.subscribe(status=>{if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){remotePending=true;show('#updates-banner');}});
}
function renderCreateProject(){hide('#project-content');show('#project-empty');$('#project-empty').innerHTML=`${head('Proyecto','Defina el reto estratégico')}${canEdit()?`<form id="create-project-form" class="section-card"><label>Título<input name="title" required></label><label>Perspectiva estratégica<select name="perspective_id"><option value="">Sin definir</option>${state.perspectives.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label>Alineación estratégica<textarea name="strategic_alignment" required></textarea></label><button class="primary-btn">Crear proyecto</button></form>`:'<p>El equipo aún no ha creado su proyecto.</p>'}`;const f=$('#create-project-form');if(f){f.onsubmit=createProject;f.oninput=()=>dirtyForms.add(f);f.onchange=()=>dirtyForms.add(f);}}
function createProject(event){event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));return run(event.submitter,async()=>{await checked(supabase.rpc('create_project',{p_team:state.team.id,p_title:values.title,p_alignment:values.strategic_alignment,p_perspective:values.perspective_id||null}));dirtyForms.delete(form);await loadWorkspace();toast('Proyecto y entregables creados.');});}

// Definiciones compartidas por altas y edición; valores de control nunca provienen de HTML arbitrario.
const DEFINITIONS={
 project:{table:'projects',state:'project',single:true,title:'Presentación general',fields:[['title','Título','text',true],['perspective_id','Perspectiva estratégica','perspective'],['strategic_alignment','Alineación estratégica','textarea',true],['executive_summary','Resumen ejecutivo','textarea']]},
 diagnosis:{table:'problem_diagnosis',state:'diagnosis',single:true,title:'Diagnóstico',fields:[['current_situation','Situación actual','textarea',true],['justification','Justificación','textarea'],['impact','Impacto','textarea'],['physical_location','Ubicación física','textarea'],['people_involved','Involucrados','textarea'],['magnitude','Magnitud','textarea'],['chronology','Perspectiva cronológica','textarea'],['root_causes','Causas raíz','textarea'],['relevant_data','Datos y métricas','textarea'],['cost_impact','Impacto económico (COP)','nonnegative'],['service_impact','Impacto en servicio','textarea'],['quality_impact','Impacto en calidad','textarea'],['organizational_capabilities','Capacidades organizacionales','textarea']]},
 objective:{table:'project_objectives',state:'objectives',title:'Objetivo',fields:[['objective_type','Tipo','select',true,[['general','General'],['specific','Específico']]],['statement','Redacción SMART','textarea',true],['metric','Métrica','text'],['baseline','Línea base','number'],['target','Meta','number'],['unit','Unidad','text'],['deadline','Fecha límite','date']]},
 alternative:{table:'solution_alternatives',state:'alternatives',title:'Alternativa',fields:[['title','Título','text',true],['description','Descripción','textarea',true],['expected_impact','Impacto esperado','textarea'],['feasibility_score','Factibilidad (1–5)','score'],['impact_score','Impacto (1–5)','score'],['cost_score','Costo favorable (1–5)','score'],['selected','Seleccionar esta alternativa','checkbox'],['selection_rationale','Justificación de selección','textarea']]},
 action:{table:'action_plan',state:'actions',title:'Acción',fields:[['objective_id','Objetivo relacionado','objective'],['action','Qué se hará','text',true],['method','Cómo se hará','textarea'],['owner_name','Responsable','text'],['start_date','Inicio','date'],['end_date','Fin','date'],['status','Estado','select',true,[['pending','Pendiente'],['in_progress','En curso'],['blocked','Bloqueada'],['completed','Completada']]],['progress','Avance (%)','percent']]},
 stakeholder:{table:'stakeholders',state:'stakeholders',title:'Involucrado',fields:[['person_name','Persona','text',true],['project_role','Rol','text',true],['functions','Funciones','textarea',true],['dedication_hours','Horas de dedicación','nonnegative'],['dedication_period','Periodicidad','text'],['area','Área','text'],['is_team_member','Integrante del equipo','checkbox']]},
 resource:{table:'project_resources',state:'resources',title:'Recurso',fields:[['resource_type','Tipo','select',true,['humano','tecnologico','financiero','fisico','informacion','otro'].map(x=>[x,x])],['description','Descripción','textarea',true],['estimated_cost','Costo estimado (COP)','nonnegative'],['availability','Disponibilidad','textarea']]},
 indicator:{table:'indicators',state:'indicators',title:'Indicador',fields:[['objective_id','Objetivo relacionado','objective'],['name','Nombre','text',true],['indicator_type','Tipo','select',true,[['eficacia','Eficacia'],['eficiencia','Eficiencia'],['impacto','Impacto']]],['formula','Fórmula','text',true],['baseline','Línea base','number'],['target','Meta','number'],['current_value','Valor actual','number'],['unit','Unidad','text'],['frequency','Frecuencia','text'],['data_source','Fuente de datos','text'],['owner_name','Responsable','text']]},
 prototype:{table:'prototype',state:'prototype',single:true,title:'Prototipo',fields:[['prototype_type','Tipo de prototipo','text'],['status','Estado','select',true,[['idea','Idea'],['design','Diseño'],['testing','Pruebas'],['validated','Validado']]],['value_proposition','Propuesta de valor','textarea'],['description','Descripción','textarea',true],['hypothesis','Hipótesis','textarea'],['validation_method','Método de validación','textarea'],['test_results','Resultados de prueba','textarea'],['evidence_url','Enlace a evidencia','url']]}
};
function field(def,record={}){
 const [name,label,type,required,choices]=def;const v=record?.[name]??'';const req=required?'required':'';
 if(type==='textarea')return `<label>${label}<textarea name="${name}" ${req}>${esc(v)}</textarea></label>`;
 if(type==='checkbox')return `<label class="checkbox-label"><input type="checkbox" name="${name}" ${v===true?'checked':''}>${label}</label>`;
 if(['select','objective','perspective'].includes(type)){const options=type==='objective'?[['','Sin vincular'],...state.objectives.map(o=>[o.id,o.statement])]:type==='perspective'?[['','Sin definir'],...state.perspectives.map(p=>[p.id,p.name])]:choices;return `<label>${label}<select name="${name}" ${req}>${options.map(([value,text])=>`<option value="${esc(value)}" ${String(v)===String(value)?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;}
 const numeric=['number','nonnegative','score','percent'].includes(type);const bounds=type==='score'?'min="1" max="5" step="1"':type==='percent'?'min="0" max="100" step="1"':type==='nonnegative'?'min="0" step="any"':numeric?'step="any"':'';
 return `<label>${label}<input name="${name}" type="${numeric?'number':type}" value="${esc(v)}" ${req} ${bounds}></label>`;
}
function formFor(type,record){const def=DEFINITIONS[type];const fields=[...def.fields];if(type==='project'&&facilitator())fields.push(['stage','Etapa','select',true,[['formulacion','Formulación'],['prototipo','Prototipo'],['shark_tank','Shark tank'],['completed','Finalizado']]],['status','Estado del proyecto','select',true,['draft','in_review','changes_requested','approved','presented'].map(x=>[x,x])]);return `<form class="section-card structured-form" data-form="${type}" data-record-id="${esc(record?.id||'')}"><h3>${record?'Editar':'Agregar'} ${def.title.toLowerCase()}</h3><fieldset ${canEdit()?'':'disabled'}>${fields.map(f=>field(f,record)).join('')}${canEdit()?`<button class="primary-btn">Guardar ${def.title.toLowerCase()}</button>${!def.single&&record?'<button class="text-btn" type="button" data-cancel-edit>Cancelar edición</button>':''}`:''}</fieldset></form>`;}
function displayValue(def,record){const [name,,type, ,choices]=def;const value=record[name];if(value===null||value===undefined||value==='')return 'Por completar';if(type==='checkbox')return value?'Sí':'No';if(type==='date')return shortDate(value);if(type==='objective')return state.objectives.find(o=>o.id===value)?.statement||'Objetivo retirado';if(type==='perspective')return state.perspectives.find(p=>p.id===value)?.name||'Sin definir';if(type==='select')return choices.find(([k])=>k===value)?.[1]||value;if(name==='estimated_cost')return money(value);return String(value);}
function recordsFor(type){const def=DEFINITIONS[type];const records=state[def.state]||[];return `<div class="record-list">${records.map(record=>`<article class="academic-record"><dl class="record-details">${def.fields.map(f=>`<div><dt>${esc(f[1])}</dt><dd>${esc(displayValue(f,record))}</dd></div>`).join('')}</dl>${canEdit()?`<div class="record-actions"><button class="ghost-btn" data-edit="${type}" data-id="${esc(record.id)}" aria-label="Editar ${def.title.toLowerCase()}: ${esc(record.title||record.name||record.statement||record.action||record.person_name||record.description)}">Editar</button><button class="danger-btn" data-delete="${type}" data-id="${esc(record.id)}" aria-label="Eliminar ${def.title.toLowerCase()}: ${esc(record.title||record.name||record.statement||record.action||record.person_name||record.description)}">Eliminar</button></div>`:''}</article>`).join('')||empty('Todavía no hay registros.')}</div>`;}
function component(type){const def=DEFINITIONS[type];const record=def.single?state[def.state]:state.editing?.type===type?state[def.state].find(r=>r.id===state.editing.id):null;return `${(canEdit()||def.single)?formFor(type,record):''}${def.single?'':recordsFor(type)}`;}
function head(kicker,title,description=''){return `<header class="section-head"><div><span class="eyebrow">${esc(kicker)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div></header>`;}
function empty(message){return `<div class="empty-state">${esc(message)}</div>`;}
function calculateProgress(){return Number(state.project?.progress||0);}
function renderNavigation(){$('#course-nav').innerHTML=SECTIONS.map(([key,label,n])=>`<button data-section="${key}" class="${key===state.section?'active':''}" ${key===state.section?'aria-current="page"':''}><span>${n}</span>${label}</button>`).join('');}
function renderSection(){if(!state.project)return;const renderers={overview:renderOverview,members:renderMembers,diagnosis:()=>head('Diagnóstico','Diagnóstico y situación actual')+component('diagnosis'),objectives:()=>head('Objetivos','Objetivos SMART')+component('objective'),alternatives:()=>head('Solución','Alternativas de solución')+component('alternative'),action:()=>head('Ejecución','Plan de acción y cronograma')+renderGantt()+component('action'),people:()=>head('Equipo y presupuesto','Involucrados y recursos')+component('stakeholder')+component('resource'),indicators:()=>head('Resultados','Indicadores de eficacia y eficiencia')+component('indicator'),prototype:()=>head('Validación','Diseño y validación del prototipo')+component('prototype'),deliverables:renderDeliverables,comments:renderComments,activity:renderActivity};$('#project-content').innerHTML=(!canEdit()?'<p class="read-only-notice">Este espacio está en modo de consulta.</p>':'')+renderers[state.section]();$('#overall-progress').textContent=`${calculateProgress()}%`;$('#overall-bar').style.width=`${calculateProgress()}%`;}
function renderOverview(){return `${head('Proyecto de aplicación',state.project.title,'Avance de ocho componentes: diagnóstico, objetivos, alternativa, plan, recursos, indicadores, validación y entregas aprobadas.')}<div class="project-metrics"><article><span>Avance académico</span><strong>${calculateProgress()}%</strong><small>Incluye validación y aprobación</small></article><article><span>Etapa</span><strong>${esc(state.project.stage)}</strong><small>${esc(state.project.status)}</small></article></div>${component('project')}`;}
function renderMembers(){return `${head('Colaboración','Integrantes del equipo')}<section class="team-roster-card"><strong>${state.participants.length}/${state.team.max_members} integrantes</strong><div class="team-roster-grid">${state.participants.map(p=>`<article class="team-member-card"><div><strong>${esc(p.full_name||p.email)}</strong><p><a href="mailto:${esc(p.email)}">${esc(p.email)}</a></p><span>${esc(p.member_role)} · ${p.can_edit?'Edición':'Consulta'}</span></div></article>`).join('')}</div></section>`;}
function renderGantt(){const dated=state.actions.filter(a=>a.start_date&&a.end_date&&a.end_date>=a.start_date);if(!dated.length)return empty('Agregue fechas válidas al plan para visualizar el cronograma.');const ms=d=>new Date(`${d}T12:00:00`).getTime();const start=Math.min(...dated.map(a=>ms(a.start_date))),end=Math.max(...dated.map(a=>ms(a.end_date))),duration=Math.max(86400000,end-start+86400000);return `<section class="gantt-card"><h3>Cronograma Gantt</h3><div class="gantt-axis"><span>${shortDate(new Date(start))}</span><span>${shortDate(new Date(end))}</span></div>${dated.map(a=>`<div class="gantt-line"><strong>${esc(a.action)}</strong><small>${shortDate(a.start_date)} → ${shortDate(a.end_date)} · ${esc(a.owner_name)}</small><div class="gantt-track" role="img" aria-label="${esc(a.action)}: ${shortDate(a.start_date)} a ${shortDate(a.end_date)}"><span style="left:${100*(ms(a.start_date)-start)/duration}%;width:${100*(ms(a.end_date)-ms(a.start_date)+86400000)/duration}%"></span></div></div>`).join('')}</section>`;}
function renderDeliverables(){return `${head('Seguimiento académico','Entregables y fechas clave','Archivos privados de hasta 25 MB. Los reemplazos se conservan en el historial.')}<div class="deliverable-list">${[...state.deliverables].sort((a,b)=>a.due_at.localeCompare(b.due_at)).map(d=>`<article><div><span class="status ${esc(d.status)}">${esc(d.status)}</span><strong>${esc(d.title)}</strong><small>Vence: ${shortDate(d.due_at)}</small><p>${esc(d.reviewer_feedback)}</p>${d.file_path?`<button class="ghost-btn" data-open-file="${esc(d.file_path)}">Abrir entrega actual</button>`:''}<details><summary>Versiones anteriores</summary>${state.versions.filter(v=>v.deliverable_id===d.id).sort((a,b)=>b.submitted_at.localeCompare(a.submitted_at)).map(v=>`<p>${shortDate(v.submitted_at)} <button class="text-btn" data-open-file="${esc(v.file_path)}">Abrir ${esc(v.file_path.split('/').pop())}</button></p>`).join('')||'<p>Sin archivos.</p>'}</details></div>${canEdit()?`<form class="upload-form" data-form="upload" data-deliverable="${esc(d.id)}"><label>Archivo para ${esc(d.title)}<input name="file" type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.xlsx,.png,.jpg,.jpeg" required></label><button class="ghost-btn">${d.file_path?'Reemplazar':'Entregar'}</button></form>`:''}</article>`).join('')}</div><section class="word-export-card"><div><h3>Borrador completo del proyecto</h3><p>Contiene los datos guardados y los resultados de los indicadores.</p></div><button class="word-download-btn" data-download-draft>Descargar borrador Word</button></section>`;}
function renderComments(){return `${head('Conversación del equipo','Comentarios y retroalimentación')}<form class="comment-form" data-form="comment"><label>Sección<select name="section"><option value="general">General</option>${SECTIONS.map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label><label>Comentario<textarea name="body" required></textarea></label><button class="primary-btn">Publicar comentario</button></form><div class="comment-list">${state.comments.map(c=>`<article><div><strong>${esc(c.author?.full_name||'Usuario del portal')}</strong><small>${shortDate(c.created_at)} · ${esc(c.section)}</small><p>${esc(c.body)}</p></div></article>`).join('')||empty('Todavía no hay comentarios.')}</div>`;}
function renderActivity(){return `${head('Trazabilidad','Historial de actividad','Registro generado por el servidor.')}<div class="record-list">${state.activity.map(a=>`<article><div><strong>${esc(a.action)} · ${esc(a.entity_type)}</strong><p>${esc(state.participants.find(p=>p.profile_id===a.actor_id)?.full_name|| (a.actor_id?'Usuario autorizado':'Sistema'))}</p><small>${new Date(a.created_at).toLocaleString('es-CO')}</small></div></article>`).join('')||empty('Todavía no hay movimientos.')}</div>`;}

function payloadFor(type,form){const def=DEFINITIONS[type];const fields=[...def.fields];if(type==='project'&&facilitator())fields.push(['stage','','text'],['status','','text']);const values=Object.fromEntries(new FormData(form));const result={};for(const [name,,kind] of fields){if(kind==='checkbox')result[name]=!!form.querySelector(`[name="${name}"]`)?.checked;else if(['number','score','percent','nonnegative'].includes(kind))result[name]=values[name]===''||values[name]===undefined?(name==='estimated_cost'||name==='progress'?0:null):Number(values[name]);else if(['date','objective','perspective'].includes(kind))result[name]=values[name]||null;else result[name]=(values[name]||'').trim();}
 if(type==='action'&&result.start_date&&result.end_date&&result.end_date<result.start_date)throw new Error('La fecha final no puede ser anterior al inicio.');
 if(type==='action'&&result.status==='completed')result.progress=100;
 if(type==='alternative'&&result.selected&&!result.selection_rationale)throw new Error('Justifique por qué seleccionó esta alternativa.');
 if(type==='prototype'&&result.evidence_url&&!/^https?:\/\//i.test(result.evidence_url))throw new Error('Use una URL de evidencia http o https.');
 return result;
}
function handleSubmit(event){event.preventDefault();const form=event.target.closest('form');if(!form)return;const type=form.dataset.form;if(type==='upload')return uploadDeliverable(form,event.submitter);return run(event.submitter,async()=>{
 if(state.loadError)throw new Error('No se completó la lectura de datos. Conserve su texto y actualice antes de guardar.');
 if(type==='comment'){await checked(supabase.from('project_comments').insert({project_id:state.project.id,section:form.elements.section.value,body:form.elements.body.value.trim(),author_id:state.user.id}));dirtyForms.delete(form);form.reset();await refreshProject();toast('Comentario publicado.');return;}
 if(!canEdit())throw new Error('Este equipo está en modo de consulta.');
 const def=DEFINITIONS[type];if(!def)return;
 const payload=payloadFor(type,form);const existing=def.single?state[def.state]:state[def.state].find(r=>r.id===form.dataset.recordId);
 if(!existing){payload.project_id=state.project.id;if(def.single)payload.updated_by=state.user.id;else payload.created_by=state.user.id;}
 const fieldset=form.querySelector('fieldset');if(fieldset)fieldset.disabled=true;
 try{const saved=await saveRow(def.table,payload,existing,def.single&&type!=='project'?'project_id':'id');dirtyForms.delete(form);if(def.single)state[def.state]=saved;else {state[def.state]=state[def.state].filter(r=>r.id!==saved.id).concat(saved);form.dataset.recordId=saved.id;}if(!hasDraft()){state.editing=null;await refreshProject();}else {remotePending=true;show('#updates-banner');}toast('Cambios guardados.');}
 finally{if(fieldset)fieldset.disabled=!canEdit();}
 });}
function handleClick(event){const button=event.target.closest('button');if(!button)return;
 if(button.hasAttribute('data-download-draft'))return downloadWordDraft(button);
 if(button.dataset.openFile)return openPrivateFile(button.dataset.openFile,button);
 if(button.hasAttribute('data-cancel-edit')){if(canLeave()){dirtyForms.clear();state.editing=null;renderSection();}return;}
 if(button.dataset.edit){if(canLeave()){dirtyForms.clear();state.editing={type:button.dataset.edit,id:button.dataset.id};renderSection();$('#project-content form input, #project-content form textarea')?.focus();}return;}
 if(button.dataset.delete&&canEdit()&&canLeave()&&confirm('¿Eliminar este registro?'))return run(button,async()=>{const def=DEFINITIONS[button.dataset.delete];const record=state[def.state].find(r=>r.id===button.dataset.id);const deleted=await checked(supabase.from(def.table).delete().eq('id',record.id).eq('version',record.version).select());if(deleted?.length!==1)throw new Error('El registro cambió o perdió permisos. Actualice antes de eliminar.');dirtyForms.clear();state.editing=null;await refreshProject();toast('Registro eliminado.');});
}
async function uploadDeliverable(form,button){const file=form.elements.file.files[0];if(!file)return;return run(button,async()=>{
 if(!canEdit()||state.loadError)throw new Error('Actualice sus permisos y datos antes de entregar.');
 if(file.size>25*1024*1024)throw new Error('El archivo supera el límite de 25 MB.');
 if(!/\.(pdf|pptx?|docx?|xlsx|png|jpe?g)$/i.test(file.name))throw new Error('Formato de archivo no permitido.');
 const d=state.deliverables.find(d=>d.id===form.dataset.deliverable);const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${state.team.id}/${state.project.id}/${d.stage}/${state.user.id}/${crypto.randomUUID()}-${safe}`;
 await checked(supabase.storage.from('deliverables').upload(path,file,{upsert:false}));
 try{await saveRow('deliverables',{file_path:path},d);}catch(error){const cleanup=await supabase.storage.from('deliverables').remove([path]);if(cleanup.error)throw new Error(`${humanError(error)} La limpieza del archivo pendiente debe revisarla administración.`);throw error;}
 dirtyForms.delete(form);form.reset();await refreshProject();toast('Entrega guardada. La versión anterior se conserva.');
 },'Subiendo…');}
function downloadWordDraft(button){if(!state.project)return;return run(button,async()=>{if(hasDraft())throw new Error('Guarde o descarte los cambios pendientes antes de exportar.');await refreshProject();if(state.loadError)throw new Error('No se puede exportar información que no pudo actualizarse.');if(!window.WordExporter)throw new Error('Recargue para cargar el generador de Word.');const filename=await window.WordExporter.downloadDraft({config,state,progress:calculateProgress()});toast(`Se descargó ${filename}.`);},'Preparando Word…');}
function permanentInviteCode(){const bytes=crypto.getRandomValues(new Uint8Array(12));return `GM26-${Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}`;}
function teamInvitationModal(){if(state.membership?.role!=='lider'||!canEdit())return;const code=permanentInviteCode();const dialog=modal(`<h2>Invitar integrantes</h2><p>Comparta el código únicamente con las personas del equipo. Puede revocarlo aquí.</p><form class="modal-form"><label>Código<input name="code" value="${code}" readonly></label><button class="primary-btn">Activar código</button></form><div class="invitation-result"></div><div class="invitation-list"></div>`,'Invitaciones del equipo');
 const load=async()=>{const list=await allRows(()=>supabase.from('invitations').select('id,created_at,revoked_at,use_count').eq('team_id',state.team.id).order('created_at',{ascending:false}));dialog.querySelector('.invitation-list').innerHTML=list.map(i=>`<p>${shortDate(i.created_at)} · ${i.use_count} ingresos · ${i.revoked_at?'Revocada':`<button class="text-btn" data-revoke="${esc(i.id)}">Revocar</button>`}</p>`).join('');};
 run(null,load);dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;return run(event.submitter,async()=>{await checked(supabase.rpc('create_invitation',{p_team:state.team.id,raw_code:code,p_role:'integrante',p_max_uses:2147483647,p_expires_at:null}));form.classList.add('hidden');dialog.dataset.dirty='false';dialog.querySelector('.invitation-result').innerHTML=`<p>Código activo:</p><strong>${code}</strong><button class="ghost-btn" data-copy-code>Copiar código</button>`;await load();});};
 dialog.addEventListener('click',event=>{const b=event.target.closest('button');if(b?.hasAttribute('data-copy-code'))run(b,async()=>{await navigator.clipboard.writeText(code);toast('Código copiado.');});if(b?.dataset.revoke)run(b,async()=>{await checked(supabase.rpc('revoke_invitation',{p_invitation:b.dataset.revoke}));await load();toast('Invitación revocada.');});});
}
})();
