(() => {
'use strict';
const {configured,supabase,escapeHtml:esc,toast,run,checked,allRows,requireBackend,saveRow,openPrivateFile,humanError,setupPanel,shortDate}=window.Portal;
const state={user:null,profile:null,assignments:[],reviews:[]};const $=s=>document.querySelector(s);const dirty=new Set();
const criteria=[['strategic_impact','Impacto estratégico'],['feasibility','Factibilidad'],['innovation','Innovación'],['evidence_quality','Calidad de evidencia'],['presentation','Presentación']];
document.addEventListener('DOMContentLoaded',initializeJury);
async function initializeJury(){try{
 if(!configured||!supabase){$('#jury-config').innerHTML=setupPanel();$('#jury-config').classList.remove('hidden');return;}
 const {session}=await checked(supabase.auth.getSession());if(!session)return deny();state.user=session.user;
 await requireBackend();state.profile=await checked(supabase.from('profiles').select('*').eq('id',state.user.id).single());
 if(!['jurado','admin','docente'].includes(state.profile.global_role)||state.profile.status!=='active'||state.profile.deleted_at)return deny();
 $('#jury-name').textContent=state.profile.full_name||state.profile.email;
 document.querySelector('[data-signout]').onclick=e=>{if(!dirty.size||confirm('¿Descartar cambios y salir?'))run(e.currentTarget,async()=>{await checked(supabase.auth.signOut());location.href='index.html';});};
 $('#jury-projects').addEventListener('input',event=>{const form=event.target.closest('form');if(form)dirty.add(form);});
 $('#jury-projects').addEventListener('submit',submitReview);
 $('#jury-projects').addEventListener('click',event=>{const button=event.target.closest('[data-open-file]');if(button)openPrivateFile(button.dataset.openFile,button);});
 window.addEventListener('beforeunload',event=>{if(dirty.size){event.preventDefault();event.returnValue='';}});
 await loadJury();$('#jury-app').classList.remove('hidden');renderJury();
 }catch(error){$('#jury-config').innerHTML=`<section class="setup-panel"><h2>No se pudo cargar el panel</h2><p>${esc(humanError(error))}</p><button class="primary-btn" onclick="location.reload()">Reintentar</button></section>`;$('#jury-config').classList.remove('hidden');}}
function deny(){$('#jury-app').classList.add('hidden');$('#jury-denied').classList.remove('hidden');}
async function loadJury(){const [assignments,reviews]=await Promise.all([allRows(()=>supabase.from('jury_assignments').select('project_id,project:projects(id,title,executive_summary,strategic_alignment,stage,team:academic_teams(name),problem_diagnosis(current_situation,impact,root_causes),prototype(description,test_results,status,evidence_url),indicators(name,indicator_type,target,current_value,unit),deliverables(id,title,file_path,submitted_at))').eq('reviewer_id',state.user.id).order('project_id')),allRows(()=>supabase.from('jury_reviews').select('*').eq('reviewer_id',state.user.id).order('id'))]);state.assignments=assignments;state.reviews=reviews;}
function renderJury(){$('#jury-projects').innerHTML=state.assignments.map(assignment=>{const p=assignment.project;if(!p)return '<p>Un proyecto asignado ya no está disponible. Actualice el panel.</p>';const review=state.reviews.find(r=>r.project_id===p.id);const evidence=/^https?:\/\//i.test(p.prototype?.evidence_url||'')?`<a href="${esc(p.prototype.evidence_url)}" target="_blank" rel="noopener noreferrer">Abrir evidencia del prototipo</a>`:'';
 return `<article class="jury-card"><header><div><span>${esc(p.team?.name||'Equipo')}</span><h2>${esc(p.title)}</h2><p>${esc(p.executive_summary||p.strategic_alignment)}</p></div><b>${review?'Evaluado':'Pendiente'}</b></header><details><summary>Ver evidencia del proyecto</summary><div class="jury-evidence"><section><strong>Problema e impacto</strong><p>${esc(p.problem_diagnosis?.current_situation)}</p><p>${esc(p.problem_diagnosis?.impact)}</p></section><section><strong>Prototipo</strong><p>${esc(p.prototype?.description)}</p><p>${esc(p.prototype?.test_results)}</p>${evidence}</section><section><strong>Indicadores</strong>${(p.indicators||[]).map(i=>`<p>${esc(i.name)} · Meta ${i.target??'—'} · Actual ${i.current_value??'—'} ${esc(i.unit)}</p>`).join('')}</section><section><strong>Archivos entregados</strong>${(p.deliverables||[]).map(d=>`<p>${esc(d.title)} · ${shortDate(d.submitted_at)} ${d.file_path?`<button class="ghost-btn" data-open-file="${esc(d.file_path)}">Abrir archivo</button>`:'Sin archivo'}</p>`).join('')}</section></div></details><form data-review-project="${esc(p.id)}" class="jury-form"><fieldset><div class="rubric-grid">${criteria.map(([key,label])=>`<label>${label}<select name="${key}" required><option value="">Seleccione…</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${review?.[key]===n?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}</div><label>Comentarios<textarea name="comments" required>${esc(review?.comments||'')}</textarea></label><label>Recomendación<textarea name="recommendation">${esc(review?.recommendation||'')}</textarea></label><button class="primary-btn">${review?'Actualizar evaluación':'Enviar evaluación'}</button></fieldset></form></article>`;}).join('')||'<div class="empty-state">No tiene proyectos asignados.</div>';}
function submitReview(event){event.preventDefault();const form=event.target.closest('form[data-review-project]');if(!form)return;const values=Object.fromEntries(new FormData(form));const projectId=form.dataset.reviewProject;for(const [key]of criteria)values[key]=Number(values[key]);values.comments=values.comments.trim();values.recommendation=values.recommendation.trim();const review=state.reviews.find(r=>r.project_id===projectId);return run(event.submitter,async()=>{const fieldset=form.querySelector('fieldset');fieldset.disabled=true;try{const payload={...values};if(!review)Object.assign(payload,{project_id:projectId,reviewer_id:state.user.id});const saved=await saveRow('jury_reviews',payload,review);state.reviews=state.reviews.filter(r=>r.project_id!==projectId).concat(saved);dirty.delete(form);if(!dirty.size){await loadJury();renderJury();}toast('Evaluación guardada.');}finally{fieldset.disabled=false;}});}
})();
