const root = document.querySelector("#preview-root");
const tabs = [...document.querySelectorAll("[data-preview]")];
const toast = document.querySelector("#preview-toast");
const participantNav = [
  ["overview", "Inicio", "00"], ["diagnosis", "Diagnóstico", "01"], ["objectives", "Objetivos SMART", "02"],
  ["alternatives", "Alternativas", "03"], ["action", "Plan de acción", "04"], ["people", "Involucrados", "05"],
  ["indicators", "Indicadores", "06"], ["prototype", "Prototipo", "P"], ["deliverables", "Entregables", "E"], ["comments", "Comentarios", "C"],
];
let view = "login";
let participantSection = "overview";
let adminSection = "overview";

tabs.forEach((tab) => tab.addEventListener("click", () => render(tab.dataset.preview)));
root.addEventListener("click", handleClick);
root.addEventListener("submit", (event) => { event.preventDefault(); message("En la versión conectada, este cambio se guarda para todo el equipo."); });
render(view);

function render(nextView) {
  view = nextView;
  tabs.forEach((tab) => tab.classList.toggle("active", tab.dataset.preview === view));
  root.innerHTML = ({ login: loginView, participant: participantView, admin: adminView, jury: juryView })[view]();
}

function handleClick(event) {
  const section = event.target.closest("[data-demo-section]");
  if (section) { participantSection = section.dataset.demoSection; render("participant"); return; }
  const admin = event.target.closest("[data-demo-admin]");
  if (admin) { adminSection = admin.dataset.demoAdmin; render("admin"); return; }
  const action = event.target.closest("[data-demo-action]");
  if (action) message(action.dataset.demoAction);
}

function loginView() {
  return `<section class="auth-layout preview-login">
    <div class="auth-story"><div class="program-brand"><img class="program-logo" src="assets/logo-terpel.png" alt="Logo de Terpel"><div><strong>Diplomado en Habilidades de Gerencia Media - Organización Terpel</strong><small>Proyecto de aplicación · 2026</small></div></div><div class="auth-copy"><span class="eyebrow light">Experiencia académica colaborativa</span><h1>Del reto estratégico<br>a una solución con <em>impacto.</em></h1><p>Formule el proyecto, diseñe el prototipo y prepare el pitch final junto con su equipo.</p><div class="stage-chips"><span>01 Formulación</span><span>02 Prototipo</span><span>03 Shark tank</span></div></div><div class="auth-deadline"><span>Próximo hito</span><strong>Formulación del proyecto</strong><time>17 de septiembre</time></div></div>
    <div class="auth-access"><div class="auth-card"><div class="auth-tabs"><button class="auth-tab active">Ingresar</button><button class="auth-tab">Crear cuenta</button></div><form class="auth-form"><h2>Bienvenido de nuevo</h2><p>Continúe el trabajo con su equipo.</p><label>Correo electrónico<input type="email" value="usuario-demo@brujulamaestria.co"></label><label>Contraseña<input type="password" value="Demo-Gerencia-2026!"></label><button class="primary-btn">Ingresar al portal →</button><button class="text-btn" type="button" data-demo-action="En producción se enviará un correo seguro de recuperación.">Olvidé mi contraseña</button><small class="form-help">Vista ficticia: recorra los perfiles desde la barra superior.</small></form></div></div>
  </section>`;
}

function participantView() {
  const completed = ["diagnosis", "objectives", "alternatives", "action", "people"];
  return `<section class="portal-shell preview-shell"><header class="portal-topbar"><div class="program-brand dark"><img class="program-logo" src="assets/logo-terpel.png" alt="Logo de Terpel"><div><strong>Diplomado en Habilidades de Gerencia Media - Organización Terpel</strong><small>Equipo Horizonte · presencial</small></div></div><div class="top-actions"><span class="save-state"><i></i>Datos protegidos</span><span class="user-pill">USUARIO-DEMO</span><button class="text-btn" data-demo-action="Esta acción cerrará la sesión real.">Salir</button></div></header><div class="portal-workspace"><aside class="course-sidebar"><div class="course-progress"><span>Progreso del proyecto</span><strong>71%</strong><div class="progress-track"><div class="progress-fill" style="width:71%"></div></div></div><nav class="course-nav">${participantNav.map(([key, label, number]) => `<button class="${participantSection === key ? "active" : ""}" data-demo-section="${key}"><span>${number}</span>${label}${completed.includes(key) ? "<i>✓</i>" : ""}</button>`).join("")}</nav><div class="guide-card"><span>Guía académica</span><strong>7 componentes</strong><p>Estructura oficial del diplomado.</p><button class="ghost-btn" data-demo-action="La versión real prepara una vista imprimible.">Vista de entrega</button></div></aside><main class="course-main">${participantContent()}</main></div></section>`;
}

function participantContent() {
  const pages = {
    overview: `${head("Proyecto de aplicación", "Optimización del relevo operativo", "Un espacio compartido para convertir una necesidad estratégica en una solución validada.")}<div class="project-metrics"><article><span>Etapa actual</span><strong>Prototipo</strong><small>Trabajo activo</small></article><article><span>Avance académico</span><strong>71%</strong><small>5 de 7 componentes</small></article><article><span>Próxima entrega</span><strong>27 oct 2026</strong><small>Guía completa</small></article></div><div class="journey"><div class="journey-step active"><b>1</b><div><strong>Formulación</strong><span>Diagnóstico y guía</span></div></div><div class="journey-line"></div><div class="journey-step active"><b>2</b><div><strong>Prototipo</strong><span>Diseño y validación</span></div></div><div class="journey-line"></div><div class="journey-step"><b>3</b><div><strong>Shark tank</strong><span>Pitch de 7 minutos</span></div></div></div><form class="section-card project-summary-form"><h3>Presentación general</h3><label>Título<input value="Optimización del relevo operativo"></label><label>Alineación estratégica<textarea>Mejorar continuidad, calidad y velocidad en los cambios de turno.</textarea></label><label>Resumen ejecutivo<textarea>Prototipo digital para estandarizar información crítica y reducir reprocesos.</textarea></label><button class="primary-btn">Guardar presentación</button></form>`,
    diagnosis: `${head("Componente 01", "Diagnóstico y situación actual", "Delimite el problema en impacto, ubicación, involucrados, magnitud y perspectiva cronológica.")}<form class="section-card structured-form"><div class="form-intro"><strong>Problema identificado</strong><span>Use datos, costos, servicio y calidad.</span></div><label>Situación actual<textarea>La información entre turnos se entrega en formatos distintos, generando omisiones y tiempos de verificación.</textarea></label><div class="dimension-grid"><label>Impacto<textarea>Demoras y reprocesos operativos.</textarea></label><label>Ubicación física<textarea>Operaciones regionales.</textarea></label><label>Involucrados<textarea>Líderes, supervisores y operadores.</textarea></label><label>Magnitud<textarea>18 minutos adicionales por relevo.</textarea></label><label>Perspectiva cronológica<textarea>Incremento durante los últimos seis meses.</textarea></label><label>Causas raíz<textarea>Falta de estándar y trazabilidad.</textarea></label></div><button class="primary-btn">Guardar diagnóstico</button></form>`,
    objectives: `${head("Componente 02", "Objetivos SMART", "Defina resultados cuantificables, alcanzables y con fecha.")}<div class="section-grid"><form class="section-card"><h3>Agregar objetivo</h3><label>Tipo<select><option>Específico</option></select></label><label>Redacción SMART<textarea>Reducir el tiempo promedio de relevo operativo.</textarea></label><button class="primary-btn">Agregar objetivo</button></form><div class="records-card"><h3>Objetivos del proyecto</h3>${record("General", "Reducir en 30% los reprocesos de relevo antes de noviembre.", "Meta 30% · 26 nov 2026")}${record("Específico", "Estandarizar el 100% de los campos críticos.", "Meta 100% · 27 oct 2026")}</div></div>`,
    alternatives: `${head("Componente 03", "Alternativas de solución", "Compare propuestas y seleccione la de mayor valor.")}<div class="indicator-board">${alternative("Formulario digital guiado", "Impacto 5 · Factibilidad 5 · Costo 4", "14/15")}${alternative("Lista de chequeo impresa", "Impacto 3 · Factibilidad 5 · Costo 5", "13/15")}${alternative("Integración al sistema operativo", "Impacto 5 · Factibilidad 2 · Costo 2", "9/15")}</div>`,
    action: `${head("Componente 04", "Plan de acción y cronograma", "Conecte acciones, responsables, fechas y avance.")}<div class="gantt-card"><div class="table-header"><h3>Cronograma colaborativo</h3><span>3 acciones</span></div>${action("Levantar campos críticos", "Laura Gómez · 18 ago → 28 ago", 100)}${action("Construir prototipo", "Carlos Ruiz · 01 sep → 30 sep", 70)}${action("Ejecutar prueba piloto", "Equipo Horizonte · 01 oct → 20 oct", 35)}</div>`,
    people: `${head("Componente 05", "Involucrados y recursos", "Asigne roles, funciones y dedicación.")}<div class="people-grid">${person("Líder de proyecto", "Laura Gómez", "Coordina alcance, responsables y entregables.")}${person("Responsable de prototipo", "Carlos Ruiz", "Diseña y prueba la experiencia digital.")}${person("Analista", "USUARIO-DEMO", "Consolida datos e indicadores.")}</div>`,
    indicators: `${head("Componente 06", "Indicadores de eficacia y eficiencia", "Defina cómo evidenciar el cumplimiento y el impacto.")}<div class="indicator-board">${indicator("Eficiencia", "Tiempo promedio de relevo", "Base 18 min", "Meta 12 min")}${indicator("Eficacia", "Relevos completos sin omisiones", "Base 72%", "Meta 95%")}</div>`,
    prototype: `${head("Entregable 02", "Diseño y validación del prototipo", "Materialice la solución y documente la evidencia.")}<form class="section-card structured-form"><div class="two-cols"><label>Tipo de prototipo<input value="Formulario web navegable"></label><label>Estado<select><option>En pruebas</option></select></label></div><label>Propuesta de valor<textarea>Un relevo consistente, rápido y trazable para todos los equipos.</textarea></label><label>Resultados de prueba<textarea>8 usuarios completaron la prueba; 7 finalizaron sin asistencia.</textarea></label><button class="primary-btn">Guardar prototipo</button></form>`,
    deliverables: `${head("Seguimiento académico", "Entregables y fechas clave", "Presente la guía, el prototipo y el pitch para revisión.")}<div class="deliverable-list">${deliverable("17", "sep", "Aprobado", "Formulación: diagnóstico y objetivos", "approved")}${deliverable("27", "oct", "En preparación", "Guía completa: ítems 3 al 7", "pending")}${deliverable("26", "nov", "Pendiente", "Presentación tipo shark tank", "pending")}</div><section class="word-export-card"><div><span>Documento editable</span><h3>Borrador completo del proyecto</h3><p>Reúne en Word la información guardada en todos los frentes, con el formato y la marca institucional de la plantilla.</p></div><button class="word-download-btn" type="button" data-demo-action="En el portal real se descargará un Word diligenciado con los datos guardados."><span class="word-file-icon">W</span><span>Descargar borrados</span></button></section>`,
    comments: `${head("Conversación del equipo", "Comentarios y retroalimentación", "Registre decisiones, preguntas y aportes.")}<form class="comment-form"><select><option>General</option></select><textarea placeholder="Escriba un comentario…"></textarea><button class="primary-btn">Publicar</button></form><div class="comment-list"><article><span class="avatar">L</span><div><div><strong>Laura Gómez</strong><span>Prototipo · hoy</span></div><p>Incorporemos la medición del tiempo directamente en la prueba piloto.</p></div></article></div>`,
  };
  return pages[participantSection] || pages.overview;
}

function adminView() {
  const nav = [["overview", "Resumen"], ["teams", "Equipos"], ["people", "Participantes"], ["deliverables", "Entregables"], ["reviews", "Evaluación"]];
  return `<section class="portal-shell preview-shell"><header class="portal-topbar admin-topbar"><div class="program-brand dark"><img class="program-logo" src="assets/logo-terpel.png" alt="Logo de Terpel"><div><strong>Diplomado en Habilidades de Gerencia Media - Organización Terpel</strong><small>Administración académica</small></div></div><div class="top-actions"><span class="user-pill">DOCENTE-DEMO</span><button class="text-btn" data-demo-action="Esta acción cerrará la sesión real.">Salir</button></div></header><div class="admin-layout"><aside class="admin-sidebar"><span class="eyebrow">Gestión</span><nav>${nav.map(([key, label]) => `<button class="${adminSection === key ? "active" : ""}" data-demo-admin="${key}">${label}</button>`).join("")}</nav><div class="security-card"><strong>Acceso protegido</strong><p>La autorización se valida también en la base de datos.</p></div></aside><main class="admin-main">${adminContent()}</main></div></section>`;
}

function adminContent() {
  if (adminSection === "overview") return `${head("Panel académico", "Visión general", "Seguimiento del diplomado, sus equipos y entregas.")}<section class="admin-stats">${stat("Equipos", "4", "2 presenciales")}${stat("Participantes", "14", "Miembros activos")}${stat("Proyectos", "4", "1 en revisión")}${stat("Entregas por revisar", "2", "Requieren retroalimentación")}</section><section class="deadline-board"><div><span>18 AGO</span><strong>Equipos</strong><small>Presencial y remoto</small></div><div><span>17 SEP</span><strong>Formulación</strong><small>Ítems 1 y 2</small></div><div><span>27 OCT</span><strong>Guía completa</strong><small>Ítems 3 al 7</small></div><div><span>26 NOV</span><strong>Shark tank</strong><small>7 minutos</small></div></section>`;
  if (adminSection === "teams") return `${head("Organización académica", "Equipos del diplomado", "Cree equipos y códigos de invitación.")}<section class="admin-table-card"><div class="table-header"><h3>Cohorte 2026</h3><button class="primary-btn" data-demo-action="Aquí se abrirá la creación de un nuevo equipo.">Crear equipo</button></div>${row("Equipo Horizonte", "Presencial", "4/4 integrantes")}${row("Equipo Impulso", "Remoto", "3/4 integrantes")}${row("Equipo Norte", "Presencial", "3/3 integrantes")}</section>`;
  if (adminSection === "people") return `${head("Accesos y roles", "Participantes", "Administre estado, rol académico y pertenencia.")}<section class="admin-table-card">${row("Laura Gómez", "Líder · Equipo Horizonte", "Activa")}${row("Carlos Ruiz", "Integrante · Equipo Horizonte", "Activo")}${row("USUARIO-DEMO", "Integrante · Equipo Horizonte", "Activo")}${row("JURADO-DEMO", "Jurado", "Activo")}</section>`;
  if (adminSection === "deliverables") return `${head("Seguimiento", "Entregables académicos", "Revise archivos privados y entregue retroalimentación.")}<section class="deliverable-admin-list">${adminDelivery("Formulación: diagnóstico y objetivos", "Equipo Horizonte", "Aprobado")}${adminDelivery("Guía completa: ítems 3 al 7", "Equipo Impulso", "Entregado")}</section>`;
  return `${head("Panel de jurados", "Evaluación de impacto", "Asigne jurados y consolide la valoración final.")}<section class="review-summary"><h3>Evaluaciones recibidas</h3><article><strong>Optimización del relevo operativo</strong><span>JURADO-DEMO</span><b>4.6/5</b><p>Problema bien sustentado y prototipo viable.</p></article></section>`;
}

function juryView() {
  return `<section class="portal-shell preview-shell"><header class="portal-topbar jury-topbar"><div class="program-brand dark"><img class="program-logo" src="assets/logo-terpel.png" alt="Logo de Terpel"><div><strong>Diplomado en Habilidades de Gerencia Media - Organización Terpel</strong><small>Panel de jurados</small></div></div><div class="top-actions"><span class="user-pill">JURADO-DEMO</span><button class="text-btn" data-demo-action="Esta acción cerrará la sesión real.">Salir</button></div></header><main class="jury-main">${head("Valoración de impacto", "Proyectos asignados", "Evalúe impacto estratégico, factibilidad, innovación, evidencia y presentación.")}<div class="jury-projects"><article class="jury-card"><header><div><span>Equipo Horizonte</span><h2>Optimización del relevo operativo</h2><p>Solución digital para estandarizar información crítica y reducir reprocesos.</p></div><b>Pendiente</b></header><details open><summary>Ver evidencia del proyecto</summary><div class="jury-evidence"><section><strong>Problema</strong><p>La información entre turnos se entrega en formatos distintos.</p></section><section><strong>Impacto</strong><p>18 minutos adicionales por relevo y riesgo de omisiones.</p></section><section><strong>Prototipo</strong><p>Formulario web navegable con campos críticos.</p><small>Prueba completada por 8 usuarios.</small></section><section><strong>Indicadores</strong><p>Tiempo promedio · Meta 12 minutos</p><p>Relevos completos · Meta 95%</p></section></div></details><form class="jury-form"><div class="rubric-grid">${score("Impacto estratégico", 5)}${score("Factibilidad", 4)}${score("Innovación", 4)}${score("Calidad de evidencia", 5)}${score("Presentación", 5)}</div><label>Comentarios<textarea>Problema bien sustentado y prototipo viable.</textarea></label><label>Recomendación<textarea>Ampliar el piloto a un segundo equipo operativo.</textarea></label><button class="primary-btn">Enviar evaluación</button></form></article></div></main></section>`;
}

function head(kicker, title, description) { return `<header class="section-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div><span class="autosave-badge">Demostración</span></header>`; }
function record(type, title, meta) { return `<article class="preview-record"><div><span class="record-type">${type}</span><strong>${title}</strong><small>${meta}</small></div></article>`; }
function alternative(title, description, value) { return `<article><div><span>Alternativa</span><strong>${title}</strong><small>${description}</small></div><div class="indicator-values"><span><b>${value}</b></span></div></article>`; }
function action(title, meta, progress) { return `<article class="action-row"><div><strong>${title}</strong><small>${meta}</small></div><select><option>En curso</option></select><input type="range" min="0" max="100" value="${progress}"><b>${progress}%</b></article>`; }
function person(role, name, description) { return `<article><span>${role}</span><strong>${name}</strong><p>${description}</p><small>4 horas por semana</small></article>`; }
function indicator(type, name, base, target) { return `<article><div><span>${type}</span><strong>${name}</strong><small>Medición semanal</small></div><div class="indicator-values"><span>${base}</span><span><b>${target}</b></span></div></article>`; }
function deliverable(day, month, status, title, statusClass) { return `<article><div class="date-block"><b>${day}</b><span>${month}</span></div><div><span class="status ${statusClass}">${status}</span><strong>${title}</strong><small>Seguimiento del equipo</small></div><button class="ghost-btn" data-demo-action="En producción se seleccionará un archivo privado.">Cargar archivo</button></article>`; }
function stat(label, value, note) { return `<article><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`; }
function row(name, detail, state) { return `<article class="review-project"><div><strong>${name}</strong><small>${detail}</small></div><span class="status approved">${state}</span><button class="ghost-btn" data-demo-action="Aquí podrá editar este registro.">Gestionar</button></article>`; }
function adminDelivery(title, team, status) { return `<article><div><span class="status submitted">${status}</span><strong>${title}</strong><small>${team}</small></div><time>27 oct 2026</time><button class="ghost-btn" data-demo-action="El archivo se abrirá con una URL privada temporal.">Abrir archivo</button><button class="text-btn" data-demo-action="Aquí podrá aprobar o solicitar cambios.">Retroalimentar</button></article>`; }
function score(label, value) { return `<label>${label}<select><option>${value}</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label>`; }
function message(text) { toast.textContent = text; toast.classList.remove("hidden"); clearTimeout(message.timer); message.timer = setTimeout(() => toast.classList.add("hidden"), 3200); }
