import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {database,as,addUser,userId} from './database-helper.mjs';
test('installation and upgrade are atomic and repeatable',async()=>{
 for(const upgrade of [false,true]){const db=await database({upgrade});try{await db.exec(await fs.readFile(new URL('../supabase/migracion-integridad-20260915.sql',import.meta.url),'utf8'));assert.equal((await db.query('select public.portal_version() as version')).rows[0].version,20260915);}finally{await db.close();}}
});

test('authorization, academic workflow, versioning and files',async t=>{
 const db=await database();
 const admin=await addUser(db,1,'admin'),teacher=await addUser(db,2,'docente'),leader=await addUser(db,3,'lider'),member=await addUser(db,4),observer=await addUser(db,5),juror=await addUser(db,6,'jurado'),outsider=await addUser(db,7),leaderB=await addUser(db,8,'lider');
 const call=(u,sql,p=[])=>as(db,u,sql,p);
 const fail=async(u,sql,p=[])=>assert.rejects(()=>call(u,sql,p));
 let team,project,teamB,projectB,objective,action,delivery,filePath;
 try{
 await t.test('new identities ignore privileged metadata',async()=>{assert.equal((await db.query('select global_role from profiles where id=$1',[member])).rows[0].global_role,'participante');});
 await t.test('leader creates team and atomic project with four deliveries',async()=>{
  team=(await call(leader,"select create_team_as_leader('Equipo A','remoto',4) as id")).rows[0].id;
  project=(await call(leader,"select create_project($1,'Proyecto A','Alineación',null) as id",[team])).rows[0].id;
  assert.equal((await db.query('select count(*)::int n from deliverables where project_id=$1',[project])).rows[0].n,4);
  const again=(await call(leader,"select create_project($1,'No sobrescribir','Otro',null) as id",[team])).rows[0].id;assert.equal(again,project);
  assert.equal((await db.query('select title from projects where id=$1',[project])).rows[0].title,'Proyecto A');
  teamB=(await call(leaderB,"select create_team_as_leader('Equipo B','remoto',3) as id")).rows[0].id;
  projectB=(await call(leaderB,"select create_project($1,'Proyecto B','Alineación',null) as id",[teamB])).rows[0].id;
 });
 await t.test('invitation joins active users, accepts normalization, maintains capacity',async()=>{await call(leader,"select create_invitation($1,'REGRESSION-INVITE','integrante',5,null)",[team]);for(const u of [member,observer])await call(u,"select join_with_invitation(' regression-invite ','Integrante')");await call(teacher,'select set_team_member($1,$2,\'observador\',false)',[team,observer]);await fail(member,"select join_with_invitation('missing-code','Fixture')");await fail(member,"select create_team_as_leader('No permitido','remoto',4)");});
 await t.test('team capacity cannot shrink below membership and name cannot be blank',async()=>{const extra=await addUser(db,9);await call(extra,"select join_with_invitation('REGRESSION-INVITE','Fixture')");await fail(admin,'update academic_teams set max_members=3 where id=$1',[team]);await fail(admin,"update academic_teams set name='   ' where id=$1",[team]);await call(admin,"select set_team_member($1,$2,'integrante',true)",[team,extra]);});
 await t.test('anonymous and unrelated users cannot read academic rows',async()=>{await db.exec('set role anon');await assert.rejects(()=>db.query('select * from projects'));await db.exec('reset role');assert.equal((await call(outsider,'select * from projects')).rows.length,0);assert.equal((await call(member,'select * from projects where id=$1',[projectB])).rows.length,0);});
 await t.test('observer writes and cross-team updates are denied',async()=>{assert.equal((await call(observer,"update projects set title='Denied' where id=$1 returning id",[project])).rows.length,0);assert.equal((await call(member,"update projects set title='Denied' where id=$1 returning id",[projectB])).rows.length,0);});
 await t.test('profiles cannot self-promote or alter deleted_at',async()=>{await fail(member,"update profiles set global_role='admin' where id=$1",[member]);await fail(member,'update profiles set deleted_at=now() where id=$1',[member]);await fail(admin,"update profiles set status='blocked' where id=$1",[admin]);});
 await t.test('academic fields and author/version are controlled server-side',async()=>{
  const r=await call(member,"insert into project_objectives(project_id,objective_type,statement,metric,target,deadline,created_by) values($1,'general','Objetivo general','Porcentaje',90,'2026-09-17',$2) returning *",[project,admin]);objective=r.rows[0];assert.equal(objective.created_by,member);
  await fail(member,"insert into project_objectives(project_id,objective_type,statement,created_by) values($1,'general','Duplicado',$2)",[project,member]);
  const update=await call(member,'update project_objectives set target=95 where id=$1 and version=$2 returning version',[objective.id,objective.version]);assert.equal(Number(update.rows[0].version),2);
  assert.equal((await call(member,'update project_objectives set target=0 where id=$1 and version=$2 returning id',[objective.id,objective.version])).rows.length,0);
  await fail(member,'update project_objectives set project_id=$1 where id=$2',[projectB,objective.id]);
  await call(member,"insert into project_objectives(project_id,objective_type,statement,metric,target,deadline,created_by) values($1,'specific','Objetivo específico','Horas',10,'2026-09-17',$2)",[project,member]);
 });
 await t.test('actions reject reverse intervals and objective from another project',async()=>{await fail(member,"insert into action_plan(project_id,action,start_date,end_date,created_by) values($1,'Acción','2026-10-01','2026-09-01',$2)",[project,member]);const other=(await call(leaderB,"insert into project_objectives(project_id,objective_type,statement,created_by) values($1,'general','B',$2) returning id",[projectB,leaderB])).rows[0].id;await fail(member,"insert into action_plan(project_id,objective_id,action,created_by) values($1,$2,'Cruce',$3)",[project,other,member]);action=(await call(member,"insert into action_plan(project_id,objective_id,action,owner_name,start_date,end_date,created_by) values($1,$2,'Acción válida','Fixture','2026-09-17','2026-09-20',$3) returning *",[project,objective.id,member])).rows[0];});
 await t.test('selection switches atomically and requires justification',async()=>{const a=(await call(member,"insert into solution_alternatives(project_id,title,description,selected,selection_rationale,created_by) values($1,'A','Descripción',true,'Mejor opción',$2) returning id",[project,member])).rows[0].id;const b=(await call(member,"insert into solution_alternatives(project_id,title,description,selected,selection_rationale,created_by) values($1,'B','Descripción',true,'Nueva evidencia',$2) returning id",[project,member])).rows[0].id;const list=await call(member,'select id from solution_alternatives where project_id=$1 and selected',[project]);assert.deepEqual(list.rows.map(r=>r.id),[b]);await fail(member,"update solution_alternatives set selection_rationale='' where id=$1",[b]);assert.notEqual(a,b);});
 await t.test('numeric values preserve zero and reject invalid inputs',async()=>{await call(member,'update problem_diagnosis set cost_impact=0 where project_id=$1',[project]);assert.equal(Number((await call(member,'select cost_impact from problem_diagnosis where project_id=$1',[project])).rows[0].cost_impact),0);await call(member,"insert into project_resources(project_id,resource_type,description,estimated_cost,created_by) values($1,'humano','Recurso',0,$2)",[project,member]);await fail(member,"insert into project_resources(project_id,resource_type,description,estimated_cost,created_by) values($1,'humano','Recurso',-1,$2)",[project,member]);});
 await t.test('comment author RPC supplies name without exposing email',async()=>{await call(leader,"insert into project_comments(project_id,body,author_id) values($1,'Comentario',$2)",[project,leader]);const comments=(await call(member,'select * from get_project_comments($1)',[project])).rows;assert.equal(comments[0].author.full_name,'Fixture 3');assert.equal(comments[0].author.email,undefined);assert.equal((await call(member,'select * from profiles where id=$1',[leader])).rows.length,0);await fail(member,"insert into activity_log(project_id,actor_id,action,entity_type,entity_id) values($1,$2,'fake','projects','fake')",[project,member]);});
 await t.test('non-jurors and unassigned jurors cannot submit grades',async()=>{await fail(member,'insert into jury_reviews(project_id,reviewer_id,strategic_impact,feasibility,innovation,evidence_quality,presentation,comments) values($1,$2,5,5,5,5,5,\'Fake\')',[projectB,member]);await fail(juror,'insert into jury_reviews(project_id,reviewer_id,strategic_impact,feasibility,innovation,evidence_quality,presentation,comments) values($1,$2,5,5,5,5,5,\'Fake\')',[project,juror]);});
 await t.test('assigned juror can read team and save complete grading only',async()=>{await call(admin,'insert into jury_assignments(project_id,reviewer_id) values($1,$2)',[project,juror]);assert.equal((await call(juror,'select name from academic_teams where id=$1',[team])).rows[0].name,'Equipo A');await fail(juror,'insert into jury_reviews(project_id,reviewer_id,strategic_impact) values($1,$2,5)',[project,juror]);await call(juror,"insert into jury_reviews(project_id,reviewer_id,strategic_impact,feasibility,innovation,evidence_quality,presentation,comments) values($1,$2,5,4,3,4,5,'Comentario')",[project,juror]);});
 await t.test('file submission is scoped, versioned and cannot self-approve',async()=>{delivery=(await call(member,"select * from deliverables where project_id=$1 and stage='formulacion'",[project])).rows[0];filePath=`${team}/${project}/formulacion/${member}/test.pdf`;await call(member,"insert into storage.objects(bucket_id,name) values('deliverables',$1)",[filePath]);await call(member,'update deliverables set file_path=$1 where id=$2',[filePath,delivery.id]);await fail(member,"update deliverables set status='approved' where id=$1",[delivery.id]);await fail(member,"update deliverables set reviewer_feedback='Fake',reviewed_by=$1 where id=$2",[teacher,delivery.id]);await fail(member,"update projects set stage='completed',status='approved' where id=$1",[project]);await call(teacher,"update deliverables set status='approved',reviewer_feedback='Revisado' where id=$1",[delivery.id]);const approved=(await call(member,'select * from deliverables where id=$1',[delivery.id])).rows[0];assert.equal(approved.reviewed_by,teacher);assert.equal(approved.submitted_by,member);assert.equal((await call(member,'select * from deliverable_versions where project_id=$1',[project])).rows.length,1);assert.equal((await call(juror,'select * from storage.objects')).rows.length,1);assert.equal((await call(outsider,'select * from storage.objects')).rows.length,0);assert.equal((await call(member,'delete from storage.objects where name=$1 returning id',[filePath])).rows.length,0);});
 await t.test('replacement retains previous file and clears prior review',async()=>{const next=`${team}/${project}/formulacion/${member}/next.pdf`;await call(member,"insert into storage.objects(bucket_id,name) values('deliverables',$1)",[next]);await call(member,'update deliverables set file_path=$1 where id=$2',[next,delivery.id]);const result=(await call(member,'select * from deliverables where id=$1',[delivery.id])).rows[0];assert.equal(result.status,'submitted');assert.equal(result.reviewed_by,null);assert.equal(result.reviewer_feedback,'');assert.equal((await call(member,'select * from deliverable_versions where project_id=$1',[project])).rows.length,2);});
 await t.test('blocked membership loses access and cannot create team',async()=>{await call(admin,"update profiles set status='blocked' where id=$1",[member]);assert.equal((await call(member,'select * from projects')).rows.length,0);assert.equal((await call(member,'select * from storage.objects')).rows.length,0);await fail(member,"select create_team_as_leader('Evasión','remoto',3)");await call(admin,"update profiles set status='active' where id=$1",[member]);});
 await t.test('deleted juror cannot edit grades or reclaim access through NULL role',async()=>{await call(admin,'select admin_remove_person($1)',[juror]);assert.equal((await call(juror,'update jury_reviews set strategic_impact=1 returning id')).rows.length,0);await fail(juror,"select create_team_as_leader('Evasión borrado','remoto',3)");});
 await t.test('archived team rejects invitations, reopening and leadership recovery work',async()=>{await call(admin,"update academic_teams set status='archived' where id=$1",[team]);await fail(leader,"select create_invitation($1,'ARCHIVED-CODE','integrante',1,null)",[team]);await fail(outsider,"select join_with_invitation('REGRESSION-INVITE','Fixture')");await call(admin,"update academic_teams set status='active' where id=$1",[team]);await call(teacher,"select set_team_member($1,$2,'lider',false)",[team,member]);assert.equal((await call(member,'select leader_id from academic_teams where id=$1',[team])).rows[0].leader_id,member);});
 await t.test('audit is server-generated and progress shared but not writable',async()=>{const log=(await call(member,'select * from activity_log where project_id=$1',[project])).rows;assert.ok(log.length>10);const progress=(await call(member,'select progress from projects where id=$1',[project])).rows[0].progress;assert.ok(progress>0&&progress<100);await fail(member,'update projects set progress=100 where id=$1',[project]);});
 await t.test('team deletion refuses orphans and supports recoverable full cleanup',async()=>{await fail(admin,"select admin_delete_team($1,'Equipo A')",[team]);await call(admin,"select prepare_team_deletion($1,'Equipo A')",[team]);assert.equal((await call(member,'update projects set title=\'Denied\' where id=$1 returning id',[project])).rows.length,0);await call(admin,"delete from storage.objects where bucket_id='deliverables' and split_part(name,'/',1)=$1",[team]);await call(admin,"select admin_delete_team($1,'Equipo A')",[team]);assert.equal((await db.query('select * from projects where id=$1',[project])).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);});
 }finally{await db.close();}
});
