import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
import {parseHTML} from 'linkedom';
process.env.TZ='America/Bogota';

class FormDataMock {
 constructor(form){if(form?.tagName!=='FORM')throw new TypeError('Expected FORM');this.entries=[...form.querySelectorAll('input,textarea,select')].filter(e=>e.name&&(!['checkbox','radio'].includes(e.type)||e.checked)).map(e=>[e.name,e.tagName==='SELECT'?(e.querySelector('option[selected]')||e.querySelector('option'))?.getAttribute('value')||'':e.value||'']);}
 [Symbol.iterator](){return this.entries[Symbol.iterator]();}
}
async function fixture(module='app',page='index',names='state,dirtyForms,DEFINITIONS,renderSection,payloadFor,fetchProjectData,refreshProject,updatePassword,createProject,subscribeRealtime,renderGantt,handleSubmit'){
 const {document}=parseHTML(await fs.readFile(new URL(`../${page}.html`,import.meta.url),'utf8'));
 const banner=document.createElement('div');banner.id='updates-banner';document.body.appendChild(banner);
 const calls=[],tables={},failures=new Set(),subscriptions=[],messages=[];
 let counter=0;
 const client={auth:{getSession:async()=>({data:{session:null},error:null}),updateUser:async()=>{await new Promise(r=>setTimeout(r,5));calls.push({auth:'update'});return {data:{},error:null};},signOut:async()=>({data:{},error:null})},rpc(name,payload){calls.push({rpc:name,payload});return builder('rpc:'+name);},removeChannel(){},channel(){const c={on(event,filter,cb){subscriptions.push({...filter,cb});return c;},subscribe(){return c;}};return c;},from:builder};
 function builder(table){let op='select',payload,single=false,filters=[],start=0,end=499;const q={select(){return q;},order(){return q;},range(a,b){start=a;end=b;return q;},eq(k,v){filters.push([k,v]);return q;},single(){single=true;return q;},maybeSingle(){single=true;return q;},insert(p){op='insert';payload=p;return q;},update(p){op='update';payload=p;return q;},delete(){op='delete';return q;},then(resolve,reject){return Promise.resolve().then(()=>{
 if(failures.has(table))return {data:null,error:{message:'Simulated read failure '+table}};
 const matches=r=>filters.every(([k,v])=>r[k]===v);let data=tables[table]||[];
 if(op==='insert'){const row={id:`new-${++counter}`,version:1,...payload};tables[table]=data.concat(row);data=[row];calls.push({table,op,payload});}
 else if(op==='update'){data=data.filter(matches).map(r=>Object.assign(r,payload,{version:r.version+1}));calls.push({table,op,payload,filters});}
 else if(op==='delete'){data=data.filter(matches);tables[table]=(tables[table]||[]).filter(r=>!matches(r));calls.push({table,op,filters});}
 else data=data.filter(matches).slice(start,end+1);
 return {data:single?(data[0]||null):data,error:null};
 }).then(resolve,reject);}};return q;}
 const location={href:'http://localhost/index.html',hash:'',search:''};
 const context={document,location,history:{replaceState(){}},URL,URLSearchParams,FormData:FormDataMock,Date,console,crypto:globalThis.crypto,setTimeout,clearTimeout,confirm:()=>true,window:{location,addEventListener(){},setTimeout,clearTimeout,PORTAL_CONFIG:{supabaseUrl:'https://fixture.supabase.co',supabasePublishableKey:'fixture'},supabase:{createClient:()=>client}}};
 context.window.history=context.history;vm.createContext(context);
 vm.runInContext(await fs.readFile(new URL('../portal-core.js',import.meta.url),'utf8'),context);
 context.window.Portal.toast=(message,tone)=>messages.push({message,tone});
 const source=await fs.readFile(new URL(`../${module}.js`,import.meta.url),'utf8');
 vm.runInContext(source.replace(/\}\)\(\);\s*$/,`window.testAPI={${names}};})();`),context);
 return {api:context.window.testAPI,Portal:context.window.Portal,context,document,calls,tables,failures,subscriptions,messages};
}
function init(f){const s=f.api.state;Object.assign(s,{user:{id:'u'},profile:{id:'u',global_role:'lider',status:'active'},membership:{role:'lider'},team:{id:'t',name:'Equipo',status:'active',max_members:4},project:{id:'p',team_id:'t',title:'Proyecto',progress:38,version:1,stage:'formulacion',status:'draft'},participants:[],perspectives:[],diagnosis:{project_id:'p',current_situation:'Guardado',cost_impact:0,version:1},prototype:{project_id:'p',description:'Prototipo',status:'idea',version:1},objectives:[],alternatives:[],actions:[],stakeholders:[],resources:[],indicators:[],deliverables:[],versions:[],comments:[],activity:[]});return s;}

test('calendar date, zero values and no destructive busy state on selects',async()=>{const f=await fixture();const s=init(f);assert.match(f.Portal.shortDate('2026-09-17'),/17/);s.section='diagnosis';f.api.renderSection();assert.equal(f.document.querySelector('[name=cost_impact]').value,'0');const {document:d}=parseHTML('<select><option value="lider" selected>Líder</option></select>');const select=d.querySelector('select');f.Portal.setBusy(select,true);f.Portal.setBusy(select,false);assert.equal(select.querySelectorAll('option').length,1);});
test('all twelve sections render including actual measurements, editing and Gantt',async()=>{const f=await fixture();const s=init(f);s.actions=[{id:'a',action:'Actividad',start_date:'2026-09-17',end_date:'2026-09-20',owner_name:'Persona'}];for(const section of ['overview','members','diagnosis','objectives','alternatives','action','people','indicators','prototype','deliverables','comments','activity']){s.section=section;f.api.renderSection();assert.ok(f.document.querySelector('#project-content h1'),section);}s.section='indicators';f.api.renderSection();assert.ok(f.document.querySelector('[name=current_value]'));assert.ok(f.document.querySelector('[name=objective_id]'));assert.match(f.api.renderGantt(),/Cronograma Gantt/);assert.equal(f.document.querySelector('#overall-progress').textContent,'38%');});
test('blank resource cost becomes zero; action dates and selected alternative are validated',async()=>{const f=await fixture();const s=init(f);s.section='people';f.api.renderSection();const resource=f.document.querySelector('[data-form=resource]');resource.querySelector('[name=description]').value='Recurso';assert.equal(f.api.payloadFor('resource',resource).estimated_cost,0);s.section='action';f.api.renderSection();const action=f.document.querySelector('form[data-form=action]');action.querySelector('[name=start_date]').value='2026-10-01';action.querySelector('[name=end_date]').value='2026-09-01';assert.throws(()=>f.api.payloadFor('action',action),/anterior/);s.section='alternatives';f.api.renderSection();const alt=f.document.querySelector('form[data-form=alternative]');alt.querySelector('[name=selected]').checked=true;assert.throws(()=>f.api.payloadFor('alternative',alt),/Justifique/);});
test('HTML user content is escaped in forms and records',async()=>{const f=await fixture();const s=init(f);s.project.title='<img src=x onerror=bad()>';f.api.renderSection();assert.equal(f.document.querySelector('#project-content img'),null);assert.match(f.document.querySelector('#project-content').innerHTML,/&lt;img/);});
test('observer has disabled academic fields and no editing buttons',async()=>{const f=await fixture();const s=init(f);s.membership.role='observador';s.section='diagnosis';f.api.renderSection();assert.ok(f.document.querySelector('fieldset').hasAttribute('disabled'));assert.equal(f.document.querySelector('fieldset button'),null);});
test('read failure rejects without replacing saved application data',async()=>{const f=await fixture();const s=init(f);const original=s.diagnosis;f.failures.add('problem_diagnosis');await assert.rejects(()=>f.api.fetchProjectData('p'),e=>/Simulated/.test(e.message));assert.equal(s.diagnosis,original);});
test('remote update does not replace a dirty form or issue a read',async()=>{const f=await fixture();const s=init(f);s.section='diagnosis';f.api.renderSection();const form=f.document.querySelector('form[data-form=diagnosis]');form.querySelector('[name=current_situation]').value='Borrador sin guardar';f.api.dirtyForms.add(form);await f.api.refreshProject();assert.equal(form.querySelector('[name=current_situation]').value,'Borrador sin guardar');assert.equal(f.document.querySelector('form[data-form=diagnosis]'),form);});
test('all editable entities are subscribed for realtime updates',async()=>{const f=await fixture();init(f);f.api.subscribeRealtime();for(const name of ['projects','problem_diagnosis','project_objectives','solution_alternatives','action_plan','stakeholders','project_resources','indicators','prototype','deliverables','project_comments','team_members','profiles'])assert.ok(f.subscriptions.some(s=>s.table===name),name);});
test('optimistic version prevents silent overwrite and returns saved record',async()=>{const f=await fixture();f.tables.projects=[{id:'p',title:'Remote',version:2}];await assert.rejects(()=>f.Portal.saveRow('projects',{title:'Old'},{id:'p',version:1}),e=>e.code==='CONFLICT');assert.equal(f.tables.projects[0].title,'Remote');const result=await f.Portal.saveRow('projects',{title:'Accepted'},{id:'p',version:2});assert.equal(result.version,3);});
test('password continuation captures form before async work',async()=>{const f=await fixture();const {document:d}=parseHTML('<form><input name="password" value="fixture-only-123"><input name="confirmation" value="fixture-only-123"><button>Guardar</button></form>');const form=d.querySelector('form');let reset=0;form.reset=()=>reset++;const event={preventDefault(){},currentTarget:form,submitter:form.querySelector('button')};const promise=f.api.updatePassword(event);event.currentTarget=null;await promise;assert.equal(reset,1);assert.ok(f.messages.some(m=>m.message.includes('Contraseña actualizada')));});
test('jury delegated submission uses actual form and project id',async()=>{const f=await fixture('jury','jury','state,renderJury,submitReview');Object.assign(f.api.state,{user:{id:'j'},profile:{status:'active',global_role:'jurado'},assignments:[{project_id:'p',project:{id:'p',title:'Proyecto',team:{name:'Equipo'},deliverables:[],indicators:[]}}],reviews:[]});f.api.renderJury();const form=f.document.querySelector('form[data-review-project]');for(const select of form.querySelectorAll('select'))select.querySelector('option[value="5"]').setAttribute('selected','');form.querySelector('[name=comments]').value='Evaluación completa';await f.api.submitReview({preventDefault(){},target:form,currentTarget:f.document.querySelector('#jury-projects'),submitter:form.querySelector('button')});const insert=f.calls.find(c=>c.table==='jury_reviews'&&c.op==='insert');assert.ok(insert);assert.equal(insert.payload.project_id,'p');assert.equal(insert.payload.reviewer_id,'j');assert.equal(insert.payload.presentation,5);assert.ok(f.messages.some(m=>m.message.includes('Evaluación guardada')));});
test('allRows fetches every page with stable independent queries',async()=>{const f=await fixture();f.tables.profiles=Array.from({length:1201},(_,i)=>({id:i}));const result=await f.Portal.allRows(()=>f.context.window.Portal.supabase.from('profiles').select('*'));assert.equal(result.length,1201);assert.equal(result[1200].id,1200);});
test('Word includes current indicator values and XML-escaped text',async()=>{const f=await fixture();vm.runInContext(await fs.readFile(new URL('../word-export.js',import.meta.url),'utf8'),f.context);const xml=f.context.window.WordExporter.buildDocumentXml({state:{project:{title:'A < B & C'},indicators:[{name:'Resultado',current_value:0,target:10,frequency:'Mensual',owner_name:'Responsable'}]}});assert.match(xml,/Actual: 0/);assert.match(xml,/Mensual/);assert.match(xml,/A &lt; B &amp; C/);});
